// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: milvus.proto
package io.milvus.grpc;

public interface CheckHealthResponseOrBuilder extends // @@protoc_insertion_point(interface_extends:milvus.proto.milvus.CheckHealthResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     *
     * @return Whether the status field is set.
     */
    boolean hasStatus();

    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     *
     * @return The status.
     */
    io.milvus.grpc.Status getStatus();

    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     */
    io.milvus.grpc.StatusOrBuilder getStatusOrBuilder();

    /**
     * <code>bool isHealthy = 2;</code>
     *
     * @return The isHealthy.
     */
    boolean getIsHealthy();

    /**
     * <code>repeated string reasons = 3;</code>
     *
     * @return A list containing the reasons.
     */
    java.util.List<java.lang.String> getReasonsList();

    /**
     * <code>repeated string reasons = 3;</code>
     *
     * @return The count of reasons.
     */
    int getReasonsCount();

    /**
     * <code>repeated string reasons = 3;</code>
     *
     * @param index The index of the element to return.
     * @return The reasons at the given index.
     */
    java.lang.String getReasons(int index);

    /**
     * <code>repeated string reasons = 3;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the reasons at the given index.
     */
    com.google.protobuf.ByteString getReasonsBytes(int index);

    /**
     * <code>repeated .milvus.proto.milvus.QuotaState quota_states = 4;</code>
     *
     * @return A list containing the quotaStates.
     */
    java.util.List<io.milvus.grpc.QuotaState> getQuotaStatesList();

    /**
     * <code>repeated .milvus.proto.milvus.QuotaState quota_states = 4;</code>
     *
     * @return The count of quotaStates.
     */
    int getQuotaStatesCount();

    /**
     * <code>repeated .milvus.proto.milvus.QuotaState quota_states = 4;</code>
     *
     * @param index The index of the element to return.
     * @return The quotaStates at the given index.
     */
    io.milvus.grpc.QuotaState getQuotaStates(int index);

    /**
     * <code>repeated .milvus.proto.milvus.QuotaState quota_states = 4;</code>
     *
     * @return A list containing the enum numeric values on the wire for quotaStates.
     */
    java.util.List<java.lang.Integer> getQuotaStatesValueList();

    /**
     * <code>repeated .milvus.proto.milvus.QuotaState quota_states = 4;</code>
     *
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of quotaStates at the given index.
     */
    int getQuotaStatesValue(int index);
}
