// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: milvus.proto
package io.milvus.grpc;

/**
 * Protobuf type {@code milvus.proto.milvus.ComponentStates}
 */
public final class ComponentStates extends com.google.protobuf.GeneratedMessageV3 implements // @@protoc_insertion_point(message_implements:milvus.proto.milvus.ComponentStates)
        ComponentStatesOrBuilder {

    private static final long serialVersionUID = 0L;

    // Use ComponentStates.newBuilder() to construct.
    private ComponentStates(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ComponentStates() {
        subcomponentStates_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new ComponentStates();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_ComponentStates_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_ComponentStates_fieldAccessorTable
                .ensureFieldAccessorsInitialized(io.milvus.grpc.ComponentStates.class,
                        io.milvus.grpc.ComponentStates.Builder.class);
    }

    private int bitField0_;

    public static final int STATE_FIELD_NUMBER = 1;

    private io.milvus.grpc.ComponentInfo state_;

    /**
     * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
     *
     * @return Whether the state field is set.
     */
    @java.lang.Override
    public boolean hasState() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
     *
     * @return The state.
     */
    @java.lang.Override
    public io.milvus.grpc.ComponentInfo getState() {
        return state_ == null ? io.milvus.grpc.ComponentInfo.getDefaultInstance() : state_;
    }

    /**
     * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
     */
    @java.lang.Override
    public io.milvus.grpc.ComponentInfoOrBuilder getStateOrBuilder() {
        return state_ == null ? io.milvus.grpc.ComponentInfo.getDefaultInstance() : state_;
    }

    public static final int SUBCOMPONENT_STATES_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private java.util.List<io.milvus.grpc.ComponentInfo> subcomponentStates_;

    /**
     * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
     */
    @java.lang.Override
    public java.util.List<io.milvus.grpc.ComponentInfo> getSubcomponentStatesList() {
        return subcomponentStates_;
    }

    /**
     * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.milvus.grpc.ComponentInfoOrBuilder> getSubcomponentStatesOrBuilderList() {
        return subcomponentStates_;
    }

    /**
     * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
     */
    @java.lang.Override
    public int getSubcomponentStatesCount() {
        return subcomponentStates_.size();
    }

    /**
     * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
     */
    @java.lang.Override
    public io.milvus.grpc.ComponentInfo getSubcomponentStates(int index) {
        return subcomponentStates_.get(index);
    }

    /**
     * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
     */
    @java.lang.Override
    public io.milvus.grpc.ComponentInfoOrBuilder getSubcomponentStatesOrBuilder(int index) {
        return subcomponentStates_.get(index);
    }

    public static final int STATUS_FIELD_NUMBER = 3;

    private io.milvus.grpc.Status status_;

    /**
     * <code>.milvus.proto.common.Status status = 3;</code>
     *
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>.milvus.proto.common.Status status = 3;</code>
     *
     * @return The status.
     */
    @java.lang.Override
    public io.milvus.grpc.Status getStatus() {
        return status_ == null ? io.milvus.grpc.Status.getDefaultInstance() : status_;
    }

    /**
     * <code>.milvus.proto.common.Status status = 3;</code>
     */
    @java.lang.Override
    public io.milvus.grpc.StatusOrBuilder getStatusOrBuilder() {
        return status_ == null ? io.milvus.grpc.Status.getDefaultInstance() : status_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(1, getState());
        }
        for (int i = 0; i < subcomponentStates_.size(); i++) {
            output.writeMessage(2, subcomponentStates_.get(i));
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            output.writeMessage(3, getStatus());
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getState());
        }
        for (int i = 0; i < subcomponentStates_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, subcomponentStates_.get(i));
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, getStatus());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof io.milvus.grpc.ComponentStates)) {
            return super.equals(obj);
        }
        io.milvus.grpc.ComponentStates other = (io.milvus.grpc.ComponentStates) obj;
        if (hasState() != other.hasState())
            return false;
        if (hasState()) {
            if (!getState().equals(other.getState()))
                return false;
        }
        if (!getSubcomponentStatesList().equals(other.getSubcomponentStatesList()))
            return false;
        if (hasStatus() != other.hasStatus())
            return false;
        if (hasStatus()) {
            if (!getStatus().equals(other.getStatus()))
                return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasState()) {
            hash = (37 * hash) + STATE_FIELD_NUMBER;
            hash = (53 * hash) + getState().hashCode();
        }
        if (getSubcomponentStatesCount() > 0) {
            hash = (37 * hash) + SUBCOMPONENT_STATES_FIELD_NUMBER;
            hash = (53 * hash) + getSubcomponentStatesList().hashCode();
        }
        if (hasStatus()) {
            hash = (37 * hash) + STATUS_FIELD_NUMBER;
            hash = (53 * hash) + getStatus().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static io.milvus.grpc.ComponentStates parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.ComponentStates parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.ComponentStates parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.ComponentStates parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.ComponentStates parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.ComponentStates parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.ComponentStates parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.ComponentStates parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.milvus.grpc.ComponentStates parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.ComponentStates parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.milvus.grpc.ComponentStates parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.ComponentStates parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(io.milvus.grpc.ComponentStates prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code milvus.proto.milvus.ComponentStates}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:milvus.proto.milvus.ComponentStates)
            io.milvus.grpc.ComponentStatesOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_ComponentStates_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_ComponentStates_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(io.milvus.grpc.ComponentStates.class,
                            io.milvus.grpc.ComponentStates.Builder.class);
        }

        // Construct using io.milvus.grpc.ComponentStates.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                getStateFieldBuilder();
                getSubcomponentStatesFieldBuilder();
                getStatusFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            state_ = null;
            if (stateBuilder_ != null) {
                stateBuilder_.dispose();
                stateBuilder_ = null;
            }
            if (subcomponentStatesBuilder_ == null) {
                subcomponentStates_ = java.util.Collections.emptyList();
            } else {
                subcomponentStates_ = null;
                subcomponentStatesBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000002);
            status_ = null;
            if (statusBuilder_ != null) {
                statusBuilder_.dispose();
                statusBuilder_ = null;
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_ComponentStates_descriptor;
        }

        @java.lang.Override
        public io.milvus.grpc.ComponentStates getDefaultInstanceForType() {
            return io.milvus.grpc.ComponentStates.getDefaultInstance();
        }

        @java.lang.Override
        public io.milvus.grpc.ComponentStates build() {
            io.milvus.grpc.ComponentStates result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public io.milvus.grpc.ComponentStates buildPartial() {
            io.milvus.grpc.ComponentStates result = new io.milvus.grpc.ComponentStates(this);
            buildPartialRepeatedFields(result);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(io.milvus.grpc.ComponentStates result) {
            if (subcomponentStatesBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0)) {
                    subcomponentStates_ = java.util.Collections.unmodifiableList(subcomponentStates_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.subcomponentStates_ = subcomponentStates_;
            } else {
                result.subcomponentStates_ = subcomponentStatesBuilder_.build();
            }
        }

        private void buildPartial0(io.milvus.grpc.ComponentStates result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.state_ = stateBuilder_ == null ? state_ : stateBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.status_ = statusBuilder_ == null ? status_ : statusBuilder_.build();
                to_bitField0_ |= 0x00000002;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof io.milvus.grpc.ComponentStates) {
                return mergeFrom((io.milvus.grpc.ComponentStates) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(io.milvus.grpc.ComponentStates other) {
            if (other == io.milvus.grpc.ComponentStates.getDefaultInstance())
                return this;
            if (other.hasState()) {
                mergeState(other.getState());
            }
            if (subcomponentStatesBuilder_ == null) {
                if (!other.subcomponentStates_.isEmpty()) {
                    if (subcomponentStates_.isEmpty()) {
                        subcomponentStates_ = other.subcomponentStates_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureSubcomponentStatesIsMutable();
                        subcomponentStates_.addAll(other.subcomponentStates_);
                    }
                    onChanged();
                }
            } else {
                if (!other.subcomponentStates_.isEmpty()) {
                    if (subcomponentStatesBuilder_.isEmpty()) {
                        subcomponentStatesBuilder_.dispose();
                        subcomponentStatesBuilder_ = null;
                        subcomponentStates_ = other.subcomponentStates_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        subcomponentStatesBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                                ? getSubcomponentStatesFieldBuilder()
                                : null;
                    } else {
                        subcomponentStatesBuilder_.addAllMessages(other.subcomponentStates_);
                    }
                }
            }
            if (other.hasStatus()) {
                mergeStatus(other.getStatus());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(getStateFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        // case 10
                        case 18: {
                            io.milvus.grpc.ComponentInfo m = input.readMessage(io.milvus.grpc.ComponentInfo.parser(),
                                    extensionRegistry);
                            if (subcomponentStatesBuilder_ == null) {
                                ensureSubcomponentStatesIsMutable();
                                subcomponentStates_.add(m);
                            } else {
                                subcomponentStatesBuilder_.addMessage(m);
                            }
                            break;
                        }
                        // case 18
                        case 26: {
                            input.readMessage(getStatusFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000004;
                            break;
                        }
                        // case 26
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                // was an endgroup tag
                                done = true;
                            }
                            break;
                        }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private io.milvus.grpc.ComponentInfo state_;

        private com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.ComponentInfo, io.milvus.grpc.ComponentInfo.Builder, io.milvus.grpc.ComponentInfoOrBuilder> stateBuilder_;

        /**
         * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
         *
         * @return Whether the state field is set.
         */
        public boolean hasState() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
         *
         * @return The state.
         */
        public io.milvus.grpc.ComponentInfo getState() {
            if (stateBuilder_ == null) {
                return state_ == null ? io.milvus.grpc.ComponentInfo.getDefaultInstance() : state_;
            } else {
                return stateBuilder_.getMessage();
            }
        }

        /**
         * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
         */
        public Builder setState(io.milvus.grpc.ComponentInfo value) {
            if (stateBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                state_ = value;
            } else {
                stateBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
         */
        public Builder setState(io.milvus.grpc.ComponentInfo.Builder builderForValue) {
            if (stateBuilder_ == null) {
                state_ = builderForValue.build();
            } else {
                stateBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
         */
        public Builder mergeState(io.milvus.grpc.ComponentInfo value) {
            if (stateBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) && state_ != null
                        && state_ != io.milvus.grpc.ComponentInfo.getDefaultInstance()) {
                    getStateBuilder().mergeFrom(value);
                } else {
                    state_ = value;
                }
            } else {
                stateBuilder_.mergeFrom(value);
            }
            if (state_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
         */
        public Builder clearState() {
            bitField0_ = (bitField0_ & ~0x00000001);
            state_ = null;
            if (stateBuilder_ != null) {
                stateBuilder_.dispose();
                stateBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
         */
        public io.milvus.grpc.ComponentInfo.Builder getStateBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return getStateFieldBuilder().getBuilder();
        }

        /**
         * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
         */
        public io.milvus.grpc.ComponentInfoOrBuilder getStateOrBuilder() {
            if (stateBuilder_ != null) {
                return stateBuilder_.getMessageOrBuilder();
            } else {
                return state_ == null ? io.milvus.grpc.ComponentInfo.getDefaultInstance() : state_;
            }
        }

        /**
         * <code>.milvus.proto.milvus.ComponentInfo state = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.ComponentInfo, io.milvus.grpc.ComponentInfo.Builder, io.milvus.grpc.ComponentInfoOrBuilder> getStateFieldBuilder() {
            if (stateBuilder_ == null) {
                stateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.ComponentInfo, io.milvus.grpc.ComponentInfo.Builder, io.milvus.grpc.ComponentInfoOrBuilder>(
                        getState(), getParentForChildren(), isClean());
                state_ = null;
            }
            return stateBuilder_;
        }

        private java.util.List<io.milvus.grpc.ComponentInfo> subcomponentStates_ = java.util.Collections.emptyList();

        private void ensureSubcomponentStatesIsMutable() {
            if (!((bitField0_ & 0x00000002) != 0)) {
                subcomponentStates_ = new java.util.ArrayList<io.milvus.grpc.ComponentInfo>(subcomponentStates_);
                bitField0_ |= 0x00000002;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<io.milvus.grpc.ComponentInfo, io.milvus.grpc.ComponentInfo.Builder, io.milvus.grpc.ComponentInfoOrBuilder> subcomponentStatesBuilder_;

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public java.util.List<io.milvus.grpc.ComponentInfo> getSubcomponentStatesList() {
            if (subcomponentStatesBuilder_ == null) {
                return java.util.Collections.unmodifiableList(subcomponentStates_);
            } else {
                return subcomponentStatesBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public int getSubcomponentStatesCount() {
            if (subcomponentStatesBuilder_ == null) {
                return subcomponentStates_.size();
            } else {
                return subcomponentStatesBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public io.milvus.grpc.ComponentInfo getSubcomponentStates(int index) {
            if (subcomponentStatesBuilder_ == null) {
                return subcomponentStates_.get(index);
            } else {
                return subcomponentStatesBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public Builder setSubcomponentStates(int index, io.milvus.grpc.ComponentInfo value) {
            if (subcomponentStatesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureSubcomponentStatesIsMutable();
                subcomponentStates_.set(index, value);
                onChanged();
            } else {
                subcomponentStatesBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public Builder setSubcomponentStates(int index, io.milvus.grpc.ComponentInfo.Builder builderForValue) {
            if (subcomponentStatesBuilder_ == null) {
                ensureSubcomponentStatesIsMutable();
                subcomponentStates_.set(index, builderForValue.build());
                onChanged();
            } else {
                subcomponentStatesBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public Builder addSubcomponentStates(io.milvus.grpc.ComponentInfo value) {
            if (subcomponentStatesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureSubcomponentStatesIsMutable();
                subcomponentStates_.add(value);
                onChanged();
            } else {
                subcomponentStatesBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public Builder addSubcomponentStates(int index, io.milvus.grpc.ComponentInfo value) {
            if (subcomponentStatesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureSubcomponentStatesIsMutable();
                subcomponentStates_.add(index, value);
                onChanged();
            } else {
                subcomponentStatesBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public Builder addSubcomponentStates(io.milvus.grpc.ComponentInfo.Builder builderForValue) {
            if (subcomponentStatesBuilder_ == null) {
                ensureSubcomponentStatesIsMutable();
                subcomponentStates_.add(builderForValue.build());
                onChanged();
            } else {
                subcomponentStatesBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public Builder addSubcomponentStates(int index, io.milvus.grpc.ComponentInfo.Builder builderForValue) {
            if (subcomponentStatesBuilder_ == null) {
                ensureSubcomponentStatesIsMutable();
                subcomponentStates_.add(index, builderForValue.build());
                onChanged();
            } else {
                subcomponentStatesBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public Builder addAllSubcomponentStates(java.lang.Iterable<? extends io.milvus.grpc.ComponentInfo> values) {
            if (subcomponentStatesBuilder_ == null) {
                ensureSubcomponentStatesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, subcomponentStates_);
                onChanged();
            } else {
                subcomponentStatesBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public Builder clearSubcomponentStates() {
            if (subcomponentStatesBuilder_ == null) {
                subcomponentStates_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                subcomponentStatesBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public Builder removeSubcomponentStates(int index) {
            if (subcomponentStatesBuilder_ == null) {
                ensureSubcomponentStatesIsMutable();
                subcomponentStates_.remove(index);
                onChanged();
            } else {
                subcomponentStatesBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public io.milvus.grpc.ComponentInfo.Builder getSubcomponentStatesBuilder(int index) {
            return getSubcomponentStatesFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public io.milvus.grpc.ComponentInfoOrBuilder getSubcomponentStatesOrBuilder(int index) {
            if (subcomponentStatesBuilder_ == null) {
                return subcomponentStates_.get(index);
            } else {
                return subcomponentStatesBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public java.util.List<? extends io.milvus.grpc.ComponentInfoOrBuilder> getSubcomponentStatesOrBuilderList() {
            if (subcomponentStatesBuilder_ != null) {
                return subcomponentStatesBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(subcomponentStates_);
            }
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public io.milvus.grpc.ComponentInfo.Builder addSubcomponentStatesBuilder() {
            return getSubcomponentStatesFieldBuilder().addBuilder(io.milvus.grpc.ComponentInfo.getDefaultInstance());
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public io.milvus.grpc.ComponentInfo.Builder addSubcomponentStatesBuilder(int index) {
            return getSubcomponentStatesFieldBuilder().addBuilder(index, io.milvus.grpc.ComponentInfo.getDefaultInstance());
        }

        /**
         * <code>repeated .milvus.proto.milvus.ComponentInfo subcomponent_states = 2;</code>
         */
        public java.util.List<io.milvus.grpc.ComponentInfo.Builder> getSubcomponentStatesBuilderList() {
            return getSubcomponentStatesFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<io.milvus.grpc.ComponentInfo, io.milvus.grpc.ComponentInfo.Builder, io.milvus.grpc.ComponentInfoOrBuilder> getSubcomponentStatesFieldBuilder() {
            if (subcomponentStatesBuilder_ == null) {
                subcomponentStatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<io.milvus.grpc.ComponentInfo, io.milvus.grpc.ComponentInfo.Builder, io.milvus.grpc.ComponentInfoOrBuilder>(
                        subcomponentStates_, ((bitField0_ & 0x00000002) != 0), getParentForChildren(), isClean());
                subcomponentStates_ = null;
            }
            return subcomponentStatesBuilder_;
        }

        private io.milvus.grpc.Status status_;

        private com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.Status, io.milvus.grpc.Status.Builder, io.milvus.grpc.StatusOrBuilder> statusBuilder_;

        /**
         * <code>.milvus.proto.common.Status status = 3;</code>
         *
         * @return Whether the status field is set.
         */
        public boolean hasStatus() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>.milvus.proto.common.Status status = 3;</code>
         *
         * @return The status.
         */
        public io.milvus.grpc.Status getStatus() {
            if (statusBuilder_ == null) {
                return status_ == null ? io.milvus.grpc.Status.getDefaultInstance() : status_;
            } else {
                return statusBuilder_.getMessage();
            }
        }

        /**
         * <code>.milvus.proto.common.Status status = 3;</code>
         */
        public Builder setStatus(io.milvus.grpc.Status value) {
            if (statusBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                status_ = value;
            } else {
                statusBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>.milvus.proto.common.Status status = 3;</code>
         */
        public Builder setStatus(io.milvus.grpc.Status.Builder builderForValue) {
            if (statusBuilder_ == null) {
                status_ = builderForValue.build();
            } else {
                statusBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>.milvus.proto.common.Status status = 3;</code>
         */
        public Builder mergeStatus(io.milvus.grpc.Status value) {
            if (statusBuilder_ == null) {
                if (((bitField0_ & 0x00000004) != 0) && status_ != null
                        && status_ != io.milvus.grpc.Status.getDefaultInstance()) {
                    getStatusBuilder().mergeFrom(value);
                } else {
                    status_ = value;
                }
            } else {
                statusBuilder_.mergeFrom(value);
            }
            if (status_ != null) {
                bitField0_ |= 0x00000004;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.milvus.proto.common.Status status = 3;</code>
         */
        public Builder clearStatus() {
            bitField0_ = (bitField0_ & ~0x00000004);
            status_ = null;
            if (statusBuilder_ != null) {
                statusBuilder_.dispose();
                statusBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.milvus.proto.common.Status status = 3;</code>
         */
        public io.milvus.grpc.Status.Builder getStatusBuilder() {
            bitField0_ |= 0x00000004;
            onChanged();
            return getStatusFieldBuilder().getBuilder();
        }

        /**
         * <code>.milvus.proto.common.Status status = 3;</code>
         */
        public io.milvus.grpc.StatusOrBuilder getStatusOrBuilder() {
            if (statusBuilder_ != null) {
                return statusBuilder_.getMessageOrBuilder();
            } else {
                return status_ == null ? io.milvus.grpc.Status.getDefaultInstance() : status_;
            }
        }

        /**
         * <code>.milvus.proto.common.Status status = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.Status, io.milvus.grpc.Status.Builder, io.milvus.grpc.StatusOrBuilder> getStatusFieldBuilder() {
            if (statusBuilder_ == null) {
                statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.Status, io.milvus.grpc.Status.Builder, io.milvus.grpc.StatusOrBuilder>(
                        getStatus(), getParentForChildren(), isClean());
                status_ = null;
            }
            return statusBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        // @@protoc_insertion_point(builder_scope:milvus.proto.milvus.ComponentStates)
    }

    // @@protoc_insertion_point(class_scope:milvus.proto.milvus.ComponentStates)
    private static final io.milvus.grpc.ComponentStates DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new io.milvus.grpc.ComponentStates();
    }

    public static io.milvus.grpc.ComponentStates getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComponentStates> PARSER = new com.google.protobuf.AbstractParser<ComponentStates>() {

        @java.lang.Override
        public ComponentStates parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<ComponentStates> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComponentStates> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public io.milvus.grpc.ComponentStates getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
