// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto
package io.milvus.grpc;

public interface FieldDataOrBuilder extends // @@protoc_insertion_point(interface_extends:milvus.proto.schema.FieldData)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.milvus.proto.schema.DataType type = 1;</code>
     *
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();

    /**
     * <code>.milvus.proto.schema.DataType type = 1;</code>
     *
     * @return The type.
     */
    io.milvus.grpc.DataType getType();

    /**
     * <code>string field_name = 2;</code>
     *
     * @return The fieldName.
     */
    java.lang.String getFieldName();

    /**
     * <code>string field_name = 2;</code>
     *
     * @return The bytes for fieldName.
     */
    com.google.protobuf.ByteString getFieldNameBytes();

    /**
     * <code>.milvus.proto.schema.ScalarField scalars = 3;</code>
     *
     * @return Whether the scalars field is set.
     */
    boolean hasScalars();

    /**
     * <code>.milvus.proto.schema.ScalarField scalars = 3;</code>
     *
     * @return The scalars.
     */
    io.milvus.grpc.ScalarField getScalars();

    /**
     * <code>.milvus.proto.schema.ScalarField scalars = 3;</code>
     */
    io.milvus.grpc.ScalarFieldOrBuilder getScalarsOrBuilder();

    /**
     * <code>.milvus.proto.schema.VectorField vectors = 4;</code>
     *
     * @return Whether the vectors field is set.
     */
    boolean hasVectors();

    /**
     * <code>.milvus.proto.schema.VectorField vectors = 4;</code>
     *
     * @return The vectors.
     */
    io.milvus.grpc.VectorField getVectors();

    /**
     * <code>.milvus.proto.schema.VectorField vectors = 4;</code>
     */
    io.milvus.grpc.VectorFieldOrBuilder getVectorsOrBuilder();

    /**
     * <code>int64 field_id = 5;</code>
     *
     * @return The fieldId.
     */
    long getFieldId();

    /**
     * <code>bool is_dynamic = 6;</code>
     *
     * @return The isDynamic.
     */
    boolean getIsDynamic();

    io.milvus.grpc.FieldData.FieldCase getFieldCase();
}
