// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto
package io.milvus.grpc;

public interface FieldSchemaOrBuilder extends // @@protoc_insertion_point(interface_extends:milvus.proto.schema.FieldSchema)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 fieldID = 1;</code>
     *
     * @return The fieldID.
     */
    long getFieldID();

    /**
     * <code>string name = 2;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 2;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();

    /**
     * <code>bool is_primary_key = 3;</code>
     *
     * @return The isPrimaryKey.
     */
    boolean getIsPrimaryKey();

    /**
     * <code>string description = 4;</code>
     *
     * @return The description.
     */
    java.lang.String getDescription();

    /**
     * <code>string description = 4;</code>
     *
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString getDescriptionBytes();

    /**
     * <code>.milvus.proto.schema.DataType data_type = 5;</code>
     *
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();

    /**
     * <code>.milvus.proto.schema.DataType data_type = 5;</code>
     *
     * @return The dataType.
     */
    io.milvus.grpc.DataType getDataType();

    /**
     * <code>repeated .milvus.proto.common.KeyValuePair type_params = 6;</code>
     */
    java.util.List<io.milvus.grpc.KeyValuePair> getTypeParamsList();

    /**
     * <code>repeated .milvus.proto.common.KeyValuePair type_params = 6;</code>
     */
    io.milvus.grpc.KeyValuePair getTypeParams(int index);

    /**
     * <code>repeated .milvus.proto.common.KeyValuePair type_params = 6;</code>
     */
    int getTypeParamsCount();

    /**
     * <code>repeated .milvus.proto.common.KeyValuePair type_params = 6;</code>
     */
    java.util.List<? extends io.milvus.grpc.KeyValuePairOrBuilder> getTypeParamsOrBuilderList();

    /**
     * <code>repeated .milvus.proto.common.KeyValuePair type_params = 6;</code>
     */
    io.milvus.grpc.KeyValuePairOrBuilder getTypeParamsOrBuilder(int index);

    /**
     * <code>repeated .milvus.proto.common.KeyValuePair index_params = 7;</code>
     */
    java.util.List<io.milvus.grpc.KeyValuePair> getIndexParamsList();

    /**
     * <code>repeated .milvus.proto.common.KeyValuePair index_params = 7;</code>
     */
    io.milvus.grpc.KeyValuePair getIndexParams(int index);

    /**
     * <code>repeated .milvus.proto.common.KeyValuePair index_params = 7;</code>
     */
    int getIndexParamsCount();

    /**
     * <code>repeated .milvus.proto.common.KeyValuePair index_params = 7;</code>
     */
    java.util.List<? extends io.milvus.grpc.KeyValuePairOrBuilder> getIndexParamsOrBuilderList();

    /**
     * <code>repeated .milvus.proto.common.KeyValuePair index_params = 7;</code>
     */
    io.milvus.grpc.KeyValuePairOrBuilder getIndexParamsOrBuilder(int index);

    /**
     * <code>bool autoID = 8;</code>
     *
     * @return The autoID.
     */
    boolean getAutoID();

    /**
     * <pre>
     * To keep compatible with older version, the default
     * </pre>
     *
     * <code>.milvus.proto.schema.FieldState state = 9;</code>
     *
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();

    /**
     * <pre>
     * To keep compatible with older version, the default
     * </pre>
     *
     * <code>.milvus.proto.schema.FieldState state = 9;</code>
     *
     * @return The state.
     */
    io.milvus.grpc.FieldState getState();

    /**
     * <pre>
     * state is `Created`.
     * </pre>
     *
     * <code>.milvus.proto.schema.DataType element_type = 10;</code>
     *
     * @return The enum numeric value on the wire for elementType.
     */
    int getElementTypeValue();

    /**
     * <pre>
     * state is `Created`.
     * </pre>
     *
     * <code>.milvus.proto.schema.DataType element_type = 10;</code>
     *
     * @return The elementType.
     */
    io.milvus.grpc.DataType getElementType();

    /**
     * <pre>
     * default_value only support scalars except array and json for now
     * </pre>
     *
     * <code>.milvus.proto.schema.ValueField default_value = 11;</code>
     *
     * @return Whether the defaultValue field is set.
     */
    boolean hasDefaultValue();

    /**
     * <pre>
     * default_value only support scalars except array and json for now
     * </pre>
     *
     * <code>.milvus.proto.schema.ValueField default_value = 11;</code>
     *
     * @return The defaultValue.
     */
    io.milvus.grpc.ValueField getDefaultValue();

    /**
     * <pre>
     * default_value only support scalars except array and json for now
     * </pre>
     *
     * <code>.milvus.proto.schema.ValueField default_value = 11;</code>
     */
    io.milvus.grpc.ValueFieldOrBuilder getDefaultValueOrBuilder();

    /**
     * <pre>
     * mark whether this field is the dynamic field
     * </pre>
     *
     * <code>bool is_dynamic = 12;</code>
     *
     * @return The isDynamic.
     */
    boolean getIsDynamic();

    /**
     * <pre>
     * enable logic partitions
     * </pre>
     *
     * <code>bool is_partition_key = 13;</code>
     *
     * @return The isPartitionKey.
     */
    boolean getIsPartitionKey();
}
