// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: milvus.proto
package io.milvus.grpc;

public interface GrantorEntityOrBuilder extends // @@protoc_insertion_point(interface_extends:milvus.proto.milvus.GrantorEntity)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.milvus.proto.milvus.UserEntity user = 1;</code>
     *
     * @return Whether the user field is set.
     */
    boolean hasUser();

    /**
     * <code>.milvus.proto.milvus.UserEntity user = 1;</code>
     *
     * @return The user.
     */
    io.milvus.grpc.UserEntity getUser();

    /**
     * <code>.milvus.proto.milvus.UserEntity user = 1;</code>
     */
    io.milvus.grpc.UserEntityOrBuilder getUserOrBuilder();

    /**
     * <code>.milvus.proto.milvus.PrivilegeEntity privilege = 2;</code>
     *
     * @return Whether the privilege field is set.
     */
    boolean hasPrivilege();

    /**
     * <code>.milvus.proto.milvus.PrivilegeEntity privilege = 2;</code>
     *
     * @return The privilege.
     */
    io.milvus.grpc.PrivilegeEntity getPrivilege();

    /**
     * <code>.milvus.proto.milvus.PrivilegeEntity privilege = 2;</code>
     */
    io.milvus.grpc.PrivilegeEntityOrBuilder getPrivilegeOrBuilder();
}
