// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto
package io.milvus.grpc;

/**
 * Protobuf type {@code milvus.proto.schema.JSONArray}
 */
public final class JSONArray extends com.google.protobuf.GeneratedMessageV3 implements // @@protoc_insertion_point(message_implements:milvus.proto.schema.JSONArray)
        JSONArrayOrBuilder {

    private static final long serialVersionUID = 0L;

    // Use JSONArray.newBuilder() to construct.
    private JSONArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private JSONArray() {
        data_ = emptyList(com.google.protobuf.ByteString.class);
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new JSONArray();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return io.milvus.grpc.SchemaProto.internal_static_milvus_proto_schema_JSONArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return io.milvus.grpc.SchemaProto.internal_static_milvus_proto_schema_JSONArray_fieldAccessorTable
                .ensureFieldAccessorsInitialized(io.milvus.grpc.JSONArray.class, io.milvus.grpc.JSONArray.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;

    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> data_ = emptyList(
            com.google.protobuf.ByteString.class);

    /**
     * <code>repeated bytes data = 1;</code>
     *
     * @return A list containing the data.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString> getDataList() {
        return data_;
    }

    /**
     * <code>repeated bytes data = 1;</code>
     *
     * @return The count of data.
     */
    public int getDataCount() {
        return data_.size();
    }

    /**
     * <code>repeated bytes data = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public com.google.protobuf.ByteString getData(int index) {
        return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        for (int i = 0; i < data_.size(); i++) {
            output.writeBytes(1, data_.get(i));
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        {
            int dataSize = 0;
            for (int i = 0; i < data_.size(); i++) {
                dataSize += com.google.protobuf.CodedOutputStream.computeBytesSizeNoTag(data_.get(i));
            }
            size += dataSize;
            size += 1 * getDataList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof io.milvus.grpc.JSONArray)) {
            return super.equals(obj);
        }
        io.milvus.grpc.JSONArray other = (io.milvus.grpc.JSONArray) obj;
        if (!getDataList().equals(other.getDataList()))
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getDataCount() > 0) {
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getDataList().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static io.milvus.grpc.JSONArray parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.JSONArray parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.JSONArray parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.JSONArray parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.JSONArray parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.JSONArray parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.JSONArray parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.JSONArray parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.milvus.grpc.JSONArray parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.JSONArray parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.milvus.grpc.JSONArray parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.JSONArray parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(io.milvus.grpc.JSONArray prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code milvus.proto.schema.JSONArray}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:milvus.proto.schema.JSONArray)
            io.milvus.grpc.JSONArrayOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return io.milvus.grpc.SchemaProto.internal_static_milvus_proto_schema_JSONArray_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return io.milvus.grpc.SchemaProto.internal_static_milvus_proto_schema_JSONArray_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(io.milvus.grpc.JSONArray.class, io.milvus.grpc.JSONArray.Builder.class);
        }

        // Construct using io.milvus.grpc.JSONArray.newBuilder()
        private Builder() {
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            data_ = emptyList(com.google.protobuf.ByteString.class);
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return io.milvus.grpc.SchemaProto.internal_static_milvus_proto_schema_JSONArray_descriptor;
        }

        @java.lang.Override
        public io.milvus.grpc.JSONArray getDefaultInstanceForType() {
            return io.milvus.grpc.JSONArray.getDefaultInstance();
        }

        @java.lang.Override
        public io.milvus.grpc.JSONArray build() {
            io.milvus.grpc.JSONArray result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public io.milvus.grpc.JSONArray buildPartial() {
            io.milvus.grpc.JSONArray result = new io.milvus.grpc.JSONArray(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(io.milvus.grpc.JSONArray result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                data_.makeImmutable();
                result.data_ = data_;
            }
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof io.milvus.grpc.JSONArray) {
                return mergeFrom((io.milvus.grpc.JSONArray) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(io.milvus.grpc.JSONArray other) {
            if (other == io.milvus.grpc.JSONArray.getDefaultInstance())
                return this;
            if (!other.data_.isEmpty()) {
                if (data_.isEmpty()) {
                    data_ = other.data_;
                    data_.makeImmutable();
                    bitField0_ |= 0x00000001;
                } else {
                    ensureDataIsMutable();
                    data_.addAll(other.data_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString v = input.readBytes();
                            ensureDataIsMutable();
                            data_.add(v);
                            break;
                        }
                        // case 10
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                // was an endgroup tag
                                done = true;
                            }
                            break;
                        }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> data_ = emptyList(
                com.google.protobuf.ByteString.class);

        private void ensureDataIsMutable() {
            if (!data_.isModifiable()) {
                data_ = makeMutableCopy(data_);
            }
            bitField0_ |= 0x00000001;
        }

        /**
         * <code>repeated bytes data = 1;</code>
         *
         * @return A list containing the data.
         */
        public java.util.List<com.google.protobuf.ByteString> getDataList() {
            data_.makeImmutable();
            return data_;
        }

        /**
         * <code>repeated bytes data = 1;</code>
         *
         * @return The count of data.
         */
        public int getDataCount() {
            return data_.size();
        }

        /**
         * <code>repeated bytes data = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The data at the given index.
         */
        public com.google.protobuf.ByteString getData(int index) {
            return data_.get(index);
        }

        /**
         * <code>repeated bytes data = 1;</code>
         *
         * @param index The index to set the value at.
         * @param value The data to set.
         * @return This builder for chaining.
         */
        public Builder setData(int index, com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureDataIsMutable();
            data_.set(index, value);
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>repeated bytes data = 1;</code>
         *
         * @param value The data to add.
         * @return This builder for chaining.
         */
        public Builder addData(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureDataIsMutable();
            data_.add(value);
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>repeated bytes data = 1;</code>
         *
         * @param values The data to add.
         * @return This builder for chaining.
         */
        public Builder addAllData(java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
            ensureDataIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(values, data_);
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>repeated bytes data = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearData() {
            data_ = emptyList(com.google.protobuf.ByteString.class);
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        // @@protoc_insertion_point(builder_scope:milvus.proto.schema.JSONArray)
    }

    // @@protoc_insertion_point(class_scope:milvus.proto.schema.JSONArray)
    private static final io.milvus.grpc.JSONArray DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new io.milvus.grpc.JSONArray();
    }

    public static io.milvus.grpc.JSONArray getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JSONArray> PARSER = new com.google.protobuf.AbstractParser<JSONArray>() {

        @java.lang.Override
        public JSONArray parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<JSONArray> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JSONArray> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public io.milvus.grpc.JSONArray getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
