// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: milvus.proto
package io.milvus.grpc;

/**
 * Protobuf type {@code milvus.proto.milvus.ListCredUsersResponse}
 */
public final class ListCredUsersResponse extends com.google.protobuf.GeneratedMessageV3 implements // @@protoc_insertion_point(message_implements:milvus.proto.milvus.ListCredUsersResponse)
        ListCredUsersResponseOrBuilder {

    private static final long serialVersionUID = 0L;

    // Use ListCredUsersResponse.newBuilder() to construct.
    private ListCredUsersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ListCredUsersResponse() {
        usernames_ = com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new ListCredUsersResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_ListCredUsersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_ListCredUsersResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(io.milvus.grpc.ListCredUsersResponse.class,
                        io.milvus.grpc.ListCredUsersResponse.Builder.class);
    }

    private int bitField0_;

    public static final int STATUS_FIELD_NUMBER = 1;

    private io.milvus.grpc.Status status_;

    /**
     * <pre>
     * Contain error_code and reason
     * </pre>
     *
     * <code>.milvus.proto.common.Status status = 1;</code>
     *
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <pre>
     * Contain error_code and reason
     * </pre>
     *
     * <code>.milvus.proto.common.Status status = 1;</code>
     *
     * @return The status.
     */
    @java.lang.Override
    public io.milvus.grpc.Status getStatus() {
        return status_ == null ? io.milvus.grpc.Status.getDefaultInstance() : status_;
    }

    /**
     * <pre>
     * Contain error_code and reason
     * </pre>
     *
     * <code>.milvus.proto.common.Status status = 1;</code>
     */
    @java.lang.Override
    public io.milvus.grpc.StatusOrBuilder getStatusOrBuilder() {
        return status_ == null ? io.milvus.grpc.Status.getDefaultInstance() : status_;
    }

    public static final int USERNAMES_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList usernames_ = com.google.protobuf.LazyStringArrayList.emptyList();

    /**
     * <pre>
     * username array
     * </pre>
     *
     * <code>repeated string usernames = 2;</code>
     *
     * @return A list containing the usernames.
     */
    public com.google.protobuf.ProtocolStringList getUsernamesList() {
        return usernames_;
    }

    /**
     * <pre>
     * username array
     * </pre>
     *
     * <code>repeated string usernames = 2;</code>
     *
     * @return The count of usernames.
     */
    public int getUsernamesCount() {
        return usernames_.size();
    }

    /**
     * <pre>
     * username array
     * </pre>
     *
     * <code>repeated string usernames = 2;</code>
     *
     * @param index The index of the element to return.
     * @return The usernames at the given index.
     */
    public java.lang.String getUsernames(int index) {
        return usernames_.get(index);
    }

    /**
     * <pre>
     * username array
     * </pre>
     *
     * <code>repeated string usernames = 2;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the usernames at the given index.
     */
    public com.google.protobuf.ByteString getUsernamesBytes(int index) {
        return usernames_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(1, getStatus());
        }
        for (int i = 0; i < usernames_.size(); i++) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, usernames_.getRaw(i));
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getStatus());
        }
        {
            int dataSize = 0;
            for (int i = 0; i < usernames_.size(); i++) {
                dataSize += computeStringSizeNoTag(usernames_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getUsernamesList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof io.milvus.grpc.ListCredUsersResponse)) {
            return super.equals(obj);
        }
        io.milvus.grpc.ListCredUsersResponse other = (io.milvus.grpc.ListCredUsersResponse) obj;
        if (hasStatus() != other.hasStatus())
            return false;
        if (hasStatus()) {
            if (!getStatus().equals(other.getStatus()))
                return false;
        }
        if (!getUsernamesList().equals(other.getUsernamesList()))
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasStatus()) {
            hash = (37 * hash) + STATUS_FIELD_NUMBER;
            hash = (53 * hash) + getStatus().hashCode();
        }
        if (getUsernamesCount() > 0) {
            hash = (37 * hash) + USERNAMES_FIELD_NUMBER;
            hash = (53 * hash) + getUsernamesList().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static io.milvus.grpc.ListCredUsersResponse parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.ListCredUsersResponse parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.ListCredUsersResponse parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.ListCredUsersResponse parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.ListCredUsersResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.ListCredUsersResponse parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.ListCredUsersResponse parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.ListCredUsersResponse parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.milvus.grpc.ListCredUsersResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.ListCredUsersResponse parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.milvus.grpc.ListCredUsersResponse parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.ListCredUsersResponse parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(io.milvus.grpc.ListCredUsersResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code milvus.proto.milvus.ListCredUsersResponse}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:milvus.proto.milvus.ListCredUsersResponse)
            io.milvus.grpc.ListCredUsersResponseOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_ListCredUsersResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_ListCredUsersResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(io.milvus.grpc.ListCredUsersResponse.class,
                            io.milvus.grpc.ListCredUsersResponse.Builder.class);
        }

        // Construct using io.milvus.grpc.ListCredUsersResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                getStatusFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            status_ = null;
            if (statusBuilder_ != null) {
                statusBuilder_.dispose();
                statusBuilder_ = null;
            }
            usernames_ = com.google.protobuf.LazyStringArrayList.emptyList();
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_ListCredUsersResponse_descriptor;
        }

        @java.lang.Override
        public io.milvus.grpc.ListCredUsersResponse getDefaultInstanceForType() {
            return io.milvus.grpc.ListCredUsersResponse.getDefaultInstance();
        }

        @java.lang.Override
        public io.milvus.grpc.ListCredUsersResponse build() {
            io.milvus.grpc.ListCredUsersResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public io.milvus.grpc.ListCredUsersResponse buildPartial() {
            io.milvus.grpc.ListCredUsersResponse result = new io.milvus.grpc.ListCredUsersResponse(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(io.milvus.grpc.ListCredUsersResponse result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.status_ = statusBuilder_ == null ? status_ : statusBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                usernames_.makeImmutable();
                result.usernames_ = usernames_;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof io.milvus.grpc.ListCredUsersResponse) {
                return mergeFrom((io.milvus.grpc.ListCredUsersResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(io.milvus.grpc.ListCredUsersResponse other) {
            if (other == io.milvus.grpc.ListCredUsersResponse.getDefaultInstance())
                return this;
            if (other.hasStatus()) {
                mergeStatus(other.getStatus());
            }
            if (!other.usernames_.isEmpty()) {
                if (usernames_.isEmpty()) {
                    usernames_ = other.usernames_;
                    bitField0_ |= 0x00000002;
                } else {
                    ensureUsernamesIsMutable();
                    usernames_.addAll(other.usernames_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(getStatusFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        // case 10
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();
                            ensureUsernamesIsMutable();
                            usernames_.add(s);
                            break;
                        }
                        // case 18
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                // was an endgroup tag
                                done = true;
                            }
                            break;
                        }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private io.milvus.grpc.Status status_;

        private com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.Status, io.milvus.grpc.Status.Builder, io.milvus.grpc.StatusOrBuilder> statusBuilder_;

        /**
         * <pre>
         * Contain error_code and reason
         * </pre>
         *
         * <code>.milvus.proto.common.Status status = 1;</code>
         *
         * @return Whether the status field is set.
         */
        public boolean hasStatus() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <pre>
         * Contain error_code and reason
         * </pre>
         *
         * <code>.milvus.proto.common.Status status = 1;</code>
         *
         * @return The status.
         */
        public io.milvus.grpc.Status getStatus() {
            if (statusBuilder_ == null) {
                return status_ == null ? io.milvus.grpc.Status.getDefaultInstance() : status_;
            } else {
                return statusBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * Contain error_code and reason
         * </pre>
         *
         * <code>.milvus.proto.common.Status status = 1;</code>
         */
        public Builder setStatus(io.milvus.grpc.Status value) {
            if (statusBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                status_ = value;
            } else {
                statusBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Contain error_code and reason
         * </pre>
         *
         * <code>.milvus.proto.common.Status status = 1;</code>
         */
        public Builder setStatus(io.milvus.grpc.Status.Builder builderForValue) {
            if (statusBuilder_ == null) {
                status_ = builderForValue.build();
            } else {
                statusBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Contain error_code and reason
         * </pre>
         *
         * <code>.milvus.proto.common.Status status = 1;</code>
         */
        public Builder mergeStatus(io.milvus.grpc.Status value) {
            if (statusBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) && status_ != null
                        && status_ != io.milvus.grpc.Status.getDefaultInstance()) {
                    getStatusBuilder().mergeFrom(value);
                } else {
                    status_ = value;
                }
            } else {
                statusBuilder_.mergeFrom(value);
            }
            if (status_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * Contain error_code and reason
         * </pre>
         *
         * <code>.milvus.proto.common.Status status = 1;</code>
         */
        public Builder clearStatus() {
            bitField0_ = (bitField0_ & ~0x00000001);
            status_ = null;
            if (statusBuilder_ != null) {
                statusBuilder_.dispose();
                statusBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Contain error_code and reason
         * </pre>
         *
         * <code>.milvus.proto.common.Status status = 1;</code>
         */
        public io.milvus.grpc.Status.Builder getStatusBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return getStatusFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * Contain error_code and reason
         * </pre>
         *
         * <code>.milvus.proto.common.Status status = 1;</code>
         */
        public io.milvus.grpc.StatusOrBuilder getStatusOrBuilder() {
            if (statusBuilder_ != null) {
                return statusBuilder_.getMessageOrBuilder();
            } else {
                return status_ == null ? io.milvus.grpc.Status.getDefaultInstance() : status_;
            }
        }

        /**
         * <pre>
         * Contain error_code and reason
         * </pre>
         *
         * <code>.milvus.proto.common.Status status = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.Status, io.milvus.grpc.Status.Builder, io.milvus.grpc.StatusOrBuilder> getStatusFieldBuilder() {
            if (statusBuilder_ == null) {
                statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.Status, io.milvus.grpc.Status.Builder, io.milvus.grpc.StatusOrBuilder>(
                        getStatus(), getParentForChildren(), isClean());
                status_ = null;
            }
            return statusBuilder_;
        }

        private com.google.protobuf.LazyStringArrayList usernames_ = com.google.protobuf.LazyStringArrayList.emptyList();

        private void ensureUsernamesIsMutable() {
            if (!usernames_.isModifiable()) {
                usernames_ = new com.google.protobuf.LazyStringArrayList(usernames_);
            }
            bitField0_ |= 0x00000002;
        }

        /**
         * <pre>
         * username array
         * </pre>
         *
         * <code>repeated string usernames = 2;</code>
         *
         * @return A list containing the usernames.
         */
        public com.google.protobuf.ProtocolStringList getUsernamesList() {
            usernames_.makeImmutable();
            return usernames_;
        }

        /**
         * <pre>
         * username array
         * </pre>
         *
         * <code>repeated string usernames = 2;</code>
         *
         * @return The count of usernames.
         */
        public int getUsernamesCount() {
            return usernames_.size();
        }

        /**
         * <pre>
         * username array
         * </pre>
         *
         * <code>repeated string usernames = 2;</code>
         *
         * @param index The index of the element to return.
         * @return The usernames at the given index.
         */
        public java.lang.String getUsernames(int index) {
            return usernames_.get(index);
        }

        /**
         * <pre>
         * username array
         * </pre>
         *
         * <code>repeated string usernames = 2;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the usernames at the given index.
         */
        public com.google.protobuf.ByteString getUsernamesBytes(int index) {
            return usernames_.getByteString(index);
        }

        /**
         * <pre>
         * username array
         * </pre>
         *
         * <code>repeated string usernames = 2;</code>
         *
         * @param index The index to set the value at.
         * @param value The usernames to set.
         * @return This builder for chaining.
         */
        public Builder setUsernames(int index, java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureUsernamesIsMutable();
            usernames_.set(index, value);
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * username array
         * </pre>
         *
         * <code>repeated string usernames = 2;</code>
         *
         * @param value The usernames to add.
         * @return This builder for chaining.
         */
        public Builder addUsernames(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureUsernamesIsMutable();
            usernames_.add(value);
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * username array
         * </pre>
         *
         * <code>repeated string usernames = 2;</code>
         *
         * @param values The usernames to add.
         * @return This builder for chaining.
         */
        public Builder addAllUsernames(java.lang.Iterable<java.lang.String> values) {
            ensureUsernamesIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(values, usernames_);
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * username array
         * </pre>
         *
         * <code>repeated string usernames = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearUsernames() {
            usernames_ = com.google.protobuf.LazyStringArrayList.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            ;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * username array
         * </pre>
         *
         * <code>repeated string usernames = 2;</code>
         *
         * @param value The bytes of the usernames to add.
         * @return This builder for chaining.
         */
        public Builder addUsernamesBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureUsernamesIsMutable();
            usernames_.add(value);
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        // @@protoc_insertion_point(builder_scope:milvus.proto.milvus.ListCredUsersResponse)
    }

    // @@protoc_insertion_point(class_scope:milvus.proto.milvus.ListCredUsersResponse)
    private static final io.milvus.grpc.ListCredUsersResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new io.milvus.grpc.ListCredUsersResponse();
    }

    public static io.milvus.grpc.ListCredUsersResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListCredUsersResponse> PARSER = new com.google.protobuf.AbstractParser<ListCredUsersResponse>() {

        @java.lang.Override
        public ListCredUsersResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<ListCredUsersResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListCredUsersResponse> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public io.milvus.grpc.ListCredUsersResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
