// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: milvus.proto
package io.milvus.grpc;

/**
 * Protobuf enum {@code milvus.proto.milvus.OperateUserRoleType}
 */
public enum OperateUserRoleType implements com.google.protobuf.ProtocolMessageEnum {

    /**
     * <code>AddUserToRole = 0;</code>
     */
    AddUserToRole(0),
    /**
     * <code>RemoveUserFromRole = 1;</code>
     */
    RemoveUserFromRole(1),
    UNRECOGNIZED(-1);

    /**
     * <code>AddUserToRole = 0;</code>
     */
    public static final int AddUserToRole_VALUE = 0;

    /**
     * <code>RemoveUserFromRole = 1;</code>
     */
    public static final int RemoveUserFromRole_VALUE = 1;

    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException("Can't get the number of an unknown enum value.");
        }
        return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OperateUserRoleType valueOf(int value) {
        return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OperateUserRoleType forNumber(int value) {
        switch (value) {
            case 0:
                return AddUserToRole;
            case 1:
                return RemoveUserFromRole;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OperateUserRoleType> internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<OperateUserRoleType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<OperateUserRoleType>() {

        public OperateUserRoleType findValueByNumber(int number) {
            return OperateUserRoleType.forNumber(number);
        }
    };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException("Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
        return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
        return io.milvus.grpc.MilvusProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final OperateUserRoleType[] VALUES = values();

    public static OperateUserRoleType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
    }

    private final int value;

    private OperateUserRoleType(int value) {
        this.value = value;
    }
}
