// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto
package io.milvus.grpc;

public interface PrivilegeExtOrBuilder extends // @@protoc_insertion_point(interface_extends:milvus.proto.common.PrivilegeExt)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.milvus.proto.common.ObjectType object_type = 1;</code>
     *
     * @return The enum numeric value on the wire for objectType.
     */
    int getObjectTypeValue();

    /**
     * <code>.milvus.proto.common.ObjectType object_type = 1;</code>
     *
     * @return The objectType.
     */
    io.milvus.grpc.ObjectType getObjectType();

    /**
     * <code>.milvus.proto.common.ObjectPrivilege object_privilege = 2;</code>
     *
     * @return The enum numeric value on the wire for objectPrivilege.
     */
    int getObjectPrivilegeValue();

    /**
     * <code>.milvus.proto.common.ObjectPrivilege object_privilege = 2;</code>
     *
     * @return The objectPrivilege.
     */
    io.milvus.grpc.ObjectPrivilege getObjectPrivilege();

    /**
     * <code>int32 object_name_index = 3;</code>
     *
     * @return The objectNameIndex.
     */
    int getObjectNameIndex();

    /**
     * <code>int32 object_name_indexs = 4;</code>
     *
     * @return The objectNameIndexs.
     */
    int getObjectNameIndexs();
}
