// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: milvus.proto
package io.milvus.grpc;

/**
 * Protobuf type {@code milvus.proto.milvus.SearchRequestV2}
 */
public final class SearchRequestV2 extends com.google.protobuf.GeneratedMessageV3 implements // @@protoc_insertion_point(message_implements:milvus.proto.milvus.SearchRequestV2)
        SearchRequestV2OrBuilder {

    private static final long serialVersionUID = 0L;

    // Use SearchRequestV2.newBuilder() to construct.
    private SearchRequestV2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private SearchRequestV2() {
        dbName_ = "";
        collectionName_ = "";
        partitionNames_ = com.google.protobuf.LazyStringArrayList.emptyList();
        requests_ = java.util.Collections.emptyList();
        rankParams_ = java.util.Collections.emptyList();
        outputFields_ = com.google.protobuf.LazyStringArrayList.emptyList();
        consistencyLevel_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new SearchRequestV2();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_SearchRequestV2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_SearchRequestV2_fieldAccessorTable
                .ensureFieldAccessorsInitialized(io.milvus.grpc.SearchRequestV2.class,
                        io.milvus.grpc.SearchRequestV2.Builder.class);
    }

    private int bitField0_;

    public static final int BASE_FIELD_NUMBER = 1;

    private io.milvus.grpc.MsgBase base_;

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>.milvus.proto.common.MsgBase base = 1;</code>
     *
     * @return Whether the base field is set.
     */
    @java.lang.Override
    public boolean hasBase() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>.milvus.proto.common.MsgBase base = 1;</code>
     *
     * @return The base.
     */
    @java.lang.Override
    public io.milvus.grpc.MsgBase getBase() {
        return base_ == null ? io.milvus.grpc.MsgBase.getDefaultInstance() : base_;
    }

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    @java.lang.Override
    public io.milvus.grpc.MsgBaseOrBuilder getBaseOrBuilder() {
        return base_ == null ? io.milvus.grpc.MsgBase.getDefaultInstance() : base_;
    }

    public static final int DB_NAME_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private volatile java.lang.Object dbName_ = "";

    /**
     * <code>string db_name = 2;</code>
     *
     * @return The dbName.
     */
    @java.lang.Override
    public java.lang.String getDbName() {
        java.lang.Object ref = dbName_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            dbName_ = s;
            return s;
        }
    }

    /**
     * <code>string db_name = 2;</code>
     *
     * @return The bytes for dbName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDbNameBytes() {
        java.lang.Object ref = dbName_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            dbName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int COLLECTION_NAME_FIELD_NUMBER = 3;

    @SuppressWarnings("serial")
    private volatile java.lang.Object collectionName_ = "";

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>string collection_name = 3;</code>
     *
     * @return The collectionName.
     */
    @java.lang.Override
    public java.lang.String getCollectionName() {
        java.lang.Object ref = collectionName_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            collectionName_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>string collection_name = 3;</code>
     *
     * @return The bytes for collectionName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCollectionNameBytes() {
        java.lang.Object ref = collectionName_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            collectionName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int PARTITION_NAMES_FIELD_NUMBER = 4;

    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList partitionNames_ = com.google.protobuf.LazyStringArrayList.emptyList();

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>repeated string partition_names = 4;</code>
     *
     * @return A list containing the partitionNames.
     */
    public com.google.protobuf.ProtocolStringList getPartitionNamesList() {
        return partitionNames_;
    }

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>repeated string partition_names = 4;</code>
     *
     * @return The count of partitionNames.
     */
    public int getPartitionNamesCount() {
        return partitionNames_.size();
    }

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>repeated string partition_names = 4;</code>
     *
     * @param index The index of the element to return.
     * @return The partitionNames at the given index.
     */
    public java.lang.String getPartitionNames(int index) {
        return partitionNames_.get(index);
    }

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>repeated string partition_names = 4;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the partitionNames at the given index.
     */
    public com.google.protobuf.ByteString getPartitionNamesBytes(int index) {
        return partitionNames_.getByteString(index);
    }

    public static final int REQUESTS_FIELD_NUMBER = 5;

    @SuppressWarnings("serial")
    private java.util.List<io.milvus.grpc.SearchRequest> requests_;

    /**
     * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
     */
    @java.lang.Override
    public java.util.List<io.milvus.grpc.SearchRequest> getRequestsList() {
        return requests_;
    }

    /**
     * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.milvus.grpc.SearchRequestOrBuilder> getRequestsOrBuilderList() {
        return requests_;
    }

    /**
     * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
     */
    @java.lang.Override
    public int getRequestsCount() {
        return requests_.size();
    }

    /**
     * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
     */
    @java.lang.Override
    public io.milvus.grpc.SearchRequest getRequests(int index) {
        return requests_.get(index);
    }

    /**
     * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
     */
    @java.lang.Override
    public io.milvus.grpc.SearchRequestOrBuilder getRequestsOrBuilder(int index) {
        return requests_.get(index);
    }

    public static final int RANK_PARAMS_FIELD_NUMBER = 6;

    @SuppressWarnings("serial")
    private java.util.List<io.milvus.grpc.KeyValuePair> rankParams_;

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
     */
    @java.lang.Override
    public java.util.List<io.milvus.grpc.KeyValuePair> getRankParamsList() {
        return rankParams_;
    }

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.milvus.grpc.KeyValuePairOrBuilder> getRankParamsOrBuilderList() {
        return rankParams_;
    }

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
     */
    @java.lang.Override
    public int getRankParamsCount() {
        return rankParams_.size();
    }

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
     */
    @java.lang.Override
    public io.milvus.grpc.KeyValuePair getRankParams(int index) {
        return rankParams_.get(index);
    }

    /**
     * <pre>
     * must
     * </pre>
     *
     * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
     */
    @java.lang.Override
    public io.milvus.grpc.KeyValuePairOrBuilder getRankParamsOrBuilder(int index) {
        return rankParams_.get(index);
    }

    public static final int TRAVEL_TIMESTAMP_FIELD_NUMBER = 7;

    private long travelTimestamp_ = 0L;

    /**
     * <code>uint64 travel_timestamp = 7;</code>
     *
     * @return The travelTimestamp.
     */
    @java.lang.Override
    public long getTravelTimestamp() {
        return travelTimestamp_;
    }

    public static final int GUARANTEE_TIMESTAMP_FIELD_NUMBER = 8;

    private long guaranteeTimestamp_ = 0L;

    /**
     * <pre>
     * guarantee_timestamp
     * </pre>
     *
     * <code>uint64 guarantee_timestamp = 8;</code>
     *
     * @return The guaranteeTimestamp.
     */
    @java.lang.Override
    public long getGuaranteeTimestamp() {
        return guaranteeTimestamp_;
    }

    public static final int NOT_RETURN_ALL_META_FIELD_NUMBER = 9;

    private boolean notReturnAllMeta_ = false;

    /**
     * <code>bool not_return_all_meta = 9;</code>
     *
     * @return The notReturnAllMeta.
     */
    @java.lang.Override
    public boolean getNotReturnAllMeta() {
        return notReturnAllMeta_;
    }

    public static final int OUTPUT_FIELDS_FIELD_NUMBER = 10;

    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList outputFields_ = com.google.protobuf.LazyStringArrayList.emptyList();

    /**
     * <code>repeated string output_fields = 10;</code>
     *
     * @return A list containing the outputFields.
     */
    public com.google.protobuf.ProtocolStringList getOutputFieldsList() {
        return outputFields_;
    }

    /**
     * <code>repeated string output_fields = 10;</code>
     *
     * @return The count of outputFields.
     */
    public int getOutputFieldsCount() {
        return outputFields_.size();
    }

    /**
     * <code>repeated string output_fields = 10;</code>
     *
     * @param index The index of the element to return.
     * @return The outputFields at the given index.
     */
    public java.lang.String getOutputFields(int index) {
        return outputFields_.get(index);
    }

    /**
     * <code>repeated string output_fields = 10;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the outputFields at the given index.
     */
    public com.google.protobuf.ByteString getOutputFieldsBytes(int index) {
        return outputFields_.getByteString(index);
    }

    public static final int CONSISTENCY_LEVEL_FIELD_NUMBER = 11;

    private int consistencyLevel_ = 0;

    /**
     * <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
     *
     * @return The enum numeric value on the wire for consistencyLevel.
     */
    @java.lang.Override
    public int getConsistencyLevelValue() {
        return consistencyLevel_;
    }

    /**
     * <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
     *
     * @return The consistencyLevel.
     */
    @java.lang.Override
    public io.milvus.grpc.ConsistencyLevel getConsistencyLevel() {
        io.milvus.grpc.ConsistencyLevel result = io.milvus.grpc.ConsistencyLevel.forNumber(consistencyLevel_);
        return result == null ? io.milvus.grpc.ConsistencyLevel.UNRECOGNIZED : result;
    }

    public static final int USE_DEFAULT_CONSISTENCY_FIELD_NUMBER = 12;

    private boolean useDefaultConsistency_ = false;

    /**
     * <code>bool use_default_consistency = 12;</code>
     *
     * @return The useDefaultConsistency.
     */
    @java.lang.Override
    public boolean getUseDefaultConsistency() {
        return useDefaultConsistency_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(1, getBase());
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dbName_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dbName_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(collectionName_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, collectionName_);
        }
        for (int i = 0; i < partitionNames_.size(); i++) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, partitionNames_.getRaw(i));
        }
        for (int i = 0; i < requests_.size(); i++) {
            output.writeMessage(5, requests_.get(i));
        }
        for (int i = 0; i < rankParams_.size(); i++) {
            output.writeMessage(6, rankParams_.get(i));
        }
        if (travelTimestamp_ != 0L) {
            output.writeUInt64(7, travelTimestamp_);
        }
        if (guaranteeTimestamp_ != 0L) {
            output.writeUInt64(8, guaranteeTimestamp_);
        }
        if (notReturnAllMeta_ != false) {
            output.writeBool(9, notReturnAllMeta_);
        }
        for (int i = 0; i < outputFields_.size(); i++) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 10, outputFields_.getRaw(i));
        }
        if (consistencyLevel_ != io.milvus.grpc.ConsistencyLevel.Strong.getNumber()) {
            output.writeEnum(11, consistencyLevel_);
        }
        if (useDefaultConsistency_ != false) {
            output.writeBool(12, useDefaultConsistency_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getBase());
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dbName_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dbName_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(collectionName_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, collectionName_);
        }
        {
            int dataSize = 0;
            for (int i = 0; i < partitionNames_.size(); i++) {
                dataSize += computeStringSizeNoTag(partitionNames_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getPartitionNamesList().size();
        }
        for (int i = 0; i < requests_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(5, requests_.get(i));
        }
        for (int i = 0; i < rankParams_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(6, rankParams_.get(i));
        }
        if (travelTimestamp_ != 0L) {
            size += com.google.protobuf.CodedOutputStream.computeUInt64Size(7, travelTimestamp_);
        }
        if (guaranteeTimestamp_ != 0L) {
            size += com.google.protobuf.CodedOutputStream.computeUInt64Size(8, guaranteeTimestamp_);
        }
        if (notReturnAllMeta_ != false) {
            size += com.google.protobuf.CodedOutputStream.computeBoolSize(9, notReturnAllMeta_);
        }
        {
            int dataSize = 0;
            for (int i = 0; i < outputFields_.size(); i++) {
                dataSize += computeStringSizeNoTag(outputFields_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getOutputFieldsList().size();
        }
        if (consistencyLevel_ != io.milvus.grpc.ConsistencyLevel.Strong.getNumber()) {
            size += com.google.protobuf.CodedOutputStream.computeEnumSize(11, consistencyLevel_);
        }
        if (useDefaultConsistency_ != false) {
            size += com.google.protobuf.CodedOutputStream.computeBoolSize(12, useDefaultConsistency_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof io.milvus.grpc.SearchRequestV2)) {
            return super.equals(obj);
        }
        io.milvus.grpc.SearchRequestV2 other = (io.milvus.grpc.SearchRequestV2) obj;
        if (hasBase() != other.hasBase())
            return false;
        if (hasBase()) {
            if (!getBase().equals(other.getBase()))
                return false;
        }
        if (!getDbName().equals(other.getDbName()))
            return false;
        if (!getCollectionName().equals(other.getCollectionName()))
            return false;
        if (!getPartitionNamesList().equals(other.getPartitionNamesList()))
            return false;
        if (!getRequestsList().equals(other.getRequestsList()))
            return false;
        if (!getRankParamsList().equals(other.getRankParamsList()))
            return false;
        if (getTravelTimestamp() != other.getTravelTimestamp())
            return false;
        if (getGuaranteeTimestamp() != other.getGuaranteeTimestamp())
            return false;
        if (getNotReturnAllMeta() != other.getNotReturnAllMeta())
            return false;
        if (!getOutputFieldsList().equals(other.getOutputFieldsList()))
            return false;
        if (consistencyLevel_ != other.consistencyLevel_)
            return false;
        if (getUseDefaultConsistency() != other.getUseDefaultConsistency())
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasBase()) {
            hash = (37 * hash) + BASE_FIELD_NUMBER;
            hash = (53 * hash) + getBase().hashCode();
        }
        hash = (37 * hash) + DB_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getDbName().hashCode();
        hash = (37 * hash) + COLLECTION_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getCollectionName().hashCode();
        if (getPartitionNamesCount() > 0) {
            hash = (37 * hash) + PARTITION_NAMES_FIELD_NUMBER;
            hash = (53 * hash) + getPartitionNamesList().hashCode();
        }
        if (getRequestsCount() > 0) {
            hash = (37 * hash) + REQUESTS_FIELD_NUMBER;
            hash = (53 * hash) + getRequestsList().hashCode();
        }
        if (getRankParamsCount() > 0) {
            hash = (37 * hash) + RANK_PARAMS_FIELD_NUMBER;
            hash = (53 * hash) + getRankParamsList().hashCode();
        }
        hash = (37 * hash) + TRAVEL_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTravelTimestamp());
        hash = (37 * hash) + GUARANTEE_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getGuaranteeTimestamp());
        hash = (37 * hash) + NOT_RETURN_ALL_META_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getNotReturnAllMeta());
        if (getOutputFieldsCount() > 0) {
            hash = (37 * hash) + OUTPUT_FIELDS_FIELD_NUMBER;
            hash = (53 * hash) + getOutputFieldsList().hashCode();
        }
        hash = (37 * hash) + CONSISTENCY_LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + consistencyLevel_;
        hash = (37 * hash) + USE_DEFAULT_CONSISTENCY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getUseDefaultConsistency());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static io.milvus.grpc.SearchRequestV2 parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.SearchRequestV2 parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.SearchRequestV2 parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.SearchRequestV2 parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.SearchRequestV2 parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.milvus.grpc.SearchRequestV2 parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.milvus.grpc.SearchRequestV2 parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.SearchRequestV2 parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.milvus.grpc.SearchRequestV2 parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.SearchRequestV2 parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.milvus.grpc.SearchRequestV2 parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static io.milvus.grpc.SearchRequestV2 parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(io.milvus.grpc.SearchRequestV2 prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code milvus.proto.milvus.SearchRequestV2}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:milvus.proto.milvus.SearchRequestV2)
            io.milvus.grpc.SearchRequestV2OrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_SearchRequestV2_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_SearchRequestV2_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(io.milvus.grpc.SearchRequestV2.class,
                            io.milvus.grpc.SearchRequestV2.Builder.class);
        }

        // Construct using io.milvus.grpc.SearchRequestV2.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                getBaseFieldBuilder();
                getRequestsFieldBuilder();
                getRankParamsFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            base_ = null;
            if (baseBuilder_ != null) {
                baseBuilder_.dispose();
                baseBuilder_ = null;
            }
            dbName_ = "";
            collectionName_ = "";
            partitionNames_ = com.google.protobuf.LazyStringArrayList.emptyList();
            if (requestsBuilder_ == null) {
                requests_ = java.util.Collections.emptyList();
            } else {
                requests_ = null;
                requestsBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000010);
            if (rankParamsBuilder_ == null) {
                rankParams_ = java.util.Collections.emptyList();
            } else {
                rankParams_ = null;
                rankParamsBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000020);
            travelTimestamp_ = 0L;
            guaranteeTimestamp_ = 0L;
            notReturnAllMeta_ = false;
            outputFields_ = com.google.protobuf.LazyStringArrayList.emptyList();
            consistencyLevel_ = 0;
            useDefaultConsistency_ = false;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_SearchRequestV2_descriptor;
        }

        @java.lang.Override
        public io.milvus.grpc.SearchRequestV2 getDefaultInstanceForType() {
            return io.milvus.grpc.SearchRequestV2.getDefaultInstance();
        }

        @java.lang.Override
        public io.milvus.grpc.SearchRequestV2 build() {
            io.milvus.grpc.SearchRequestV2 result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public io.milvus.grpc.SearchRequestV2 buildPartial() {
            io.milvus.grpc.SearchRequestV2 result = new io.milvus.grpc.SearchRequestV2(this);
            buildPartialRepeatedFields(result);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(io.milvus.grpc.SearchRequestV2 result) {
            if (requestsBuilder_ == null) {
                if (((bitField0_ & 0x00000010) != 0)) {
                    requests_ = java.util.Collections.unmodifiableList(requests_);
                    bitField0_ = (bitField0_ & ~0x00000010);
                }
                result.requests_ = requests_;
            } else {
                result.requests_ = requestsBuilder_.build();
            }
            if (rankParamsBuilder_ == null) {
                if (((bitField0_ & 0x00000020) != 0)) {
                    rankParams_ = java.util.Collections.unmodifiableList(rankParams_);
                    bitField0_ = (bitField0_ & ~0x00000020);
                }
                result.rankParams_ = rankParams_;
            } else {
                result.rankParams_ = rankParamsBuilder_.build();
            }
        }

        private void buildPartial0(io.milvus.grpc.SearchRequestV2 result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.base_ = baseBuilder_ == null ? base_ : baseBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.dbName_ = dbName_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.collectionName_ = collectionName_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                partitionNames_.makeImmutable();
                result.partitionNames_ = partitionNames_;
            }
            if (((from_bitField0_ & 0x00000040) != 0)) {
                result.travelTimestamp_ = travelTimestamp_;
            }
            if (((from_bitField0_ & 0x00000080) != 0)) {
                result.guaranteeTimestamp_ = guaranteeTimestamp_;
            }
            if (((from_bitField0_ & 0x00000100) != 0)) {
                result.notReturnAllMeta_ = notReturnAllMeta_;
            }
            if (((from_bitField0_ & 0x00000200) != 0)) {
                outputFields_.makeImmutable();
                result.outputFields_ = outputFields_;
            }
            if (((from_bitField0_ & 0x00000400) != 0)) {
                result.consistencyLevel_ = consistencyLevel_;
            }
            if (((from_bitField0_ & 0x00000800) != 0)) {
                result.useDefaultConsistency_ = useDefaultConsistency_;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof io.milvus.grpc.SearchRequestV2) {
                return mergeFrom((io.milvus.grpc.SearchRequestV2) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(io.milvus.grpc.SearchRequestV2 other) {
            if (other == io.milvus.grpc.SearchRequestV2.getDefaultInstance())
                return this;
            if (other.hasBase()) {
                mergeBase(other.getBase());
            }
            if (!other.getDbName().isEmpty()) {
                dbName_ = other.dbName_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (!other.getCollectionName().isEmpty()) {
                collectionName_ = other.collectionName_;
                bitField0_ |= 0x00000004;
                onChanged();
            }
            if (!other.partitionNames_.isEmpty()) {
                if (partitionNames_.isEmpty()) {
                    partitionNames_ = other.partitionNames_;
                    bitField0_ |= 0x00000008;
                } else {
                    ensurePartitionNamesIsMutable();
                    partitionNames_.addAll(other.partitionNames_);
                }
                onChanged();
            }
            if (requestsBuilder_ == null) {
                if (!other.requests_.isEmpty()) {
                    if (requests_.isEmpty()) {
                        requests_ = other.requests_;
                        bitField0_ = (bitField0_ & ~0x00000010);
                    } else {
                        ensureRequestsIsMutable();
                        requests_.addAll(other.requests_);
                    }
                    onChanged();
                }
            } else {
                if (!other.requests_.isEmpty()) {
                    if (requestsBuilder_.isEmpty()) {
                        requestsBuilder_.dispose();
                        requestsBuilder_ = null;
                        requests_ = other.requests_;
                        bitField0_ = (bitField0_ & ~0x00000010);
                        requestsBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                                ? getRequestsFieldBuilder()
                                : null;
                    } else {
                        requestsBuilder_.addAllMessages(other.requests_);
                    }
                }
            }
            if (rankParamsBuilder_ == null) {
                if (!other.rankParams_.isEmpty()) {
                    if (rankParams_.isEmpty()) {
                        rankParams_ = other.rankParams_;
                        bitField0_ = (bitField0_ & ~0x00000020);
                    } else {
                        ensureRankParamsIsMutable();
                        rankParams_.addAll(other.rankParams_);
                    }
                    onChanged();
                }
            } else {
                if (!other.rankParams_.isEmpty()) {
                    if (rankParamsBuilder_.isEmpty()) {
                        rankParamsBuilder_.dispose();
                        rankParamsBuilder_ = null;
                        rankParams_ = other.rankParams_;
                        bitField0_ = (bitField0_ & ~0x00000020);
                        rankParamsBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                                ? getRankParamsFieldBuilder()
                                : null;
                    } else {
                        rankParamsBuilder_.addAllMessages(other.rankParams_);
                    }
                }
            }
            if (other.getTravelTimestamp() != 0L) {
                setTravelTimestamp(other.getTravelTimestamp());
            }
            if (other.getGuaranteeTimestamp() != 0L) {
                setGuaranteeTimestamp(other.getGuaranteeTimestamp());
            }
            if (other.getNotReturnAllMeta() != false) {
                setNotReturnAllMeta(other.getNotReturnAllMeta());
            }
            if (!other.outputFields_.isEmpty()) {
                if (outputFields_.isEmpty()) {
                    outputFields_ = other.outputFields_;
                    bitField0_ |= 0x00000200;
                } else {
                    ensureOutputFieldsIsMutable();
                    outputFields_.addAll(other.outputFields_);
                }
                onChanged();
            }
            if (other.consistencyLevel_ != 0) {
                setConsistencyLevelValue(other.getConsistencyLevelValue());
            }
            if (other.getUseDefaultConsistency() != false) {
                setUseDefaultConsistency(other.getUseDefaultConsistency());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(getBaseFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        // case 10
                        case 18: {
                            dbName_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000002;
                            break;
                        }
                        // case 18
                        case 26: {
                            collectionName_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000004;
                            break;
                        }
                        // case 26
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();
                            ensurePartitionNamesIsMutable();
                            partitionNames_.add(s);
                            break;
                        }
                        // case 34
                        case 42: {
                            io.milvus.grpc.SearchRequest m = input.readMessage(io.milvus.grpc.SearchRequest.parser(),
                                    extensionRegistry);
                            if (requestsBuilder_ == null) {
                                ensureRequestsIsMutable();
                                requests_.add(m);
                            } else {
                                requestsBuilder_.addMessage(m);
                            }
                            break;
                        }
                        // case 42
                        case 50: {
                            io.milvus.grpc.KeyValuePair m = input.readMessage(io.milvus.grpc.KeyValuePair.parser(),
                                    extensionRegistry);
                            if (rankParamsBuilder_ == null) {
                                ensureRankParamsIsMutable();
                                rankParams_.add(m);
                            } else {
                                rankParamsBuilder_.addMessage(m);
                            }
                            break;
                        }
                        // case 50
                        case 56: {
                            travelTimestamp_ = input.readUInt64();
                            bitField0_ |= 0x00000040;
                            break;
                        }
                        // case 56
                        case 64: {
                            guaranteeTimestamp_ = input.readUInt64();
                            bitField0_ |= 0x00000080;
                            break;
                        }
                        // case 64
                        case 72: {
                            notReturnAllMeta_ = input.readBool();
                            bitField0_ |= 0x00000100;
                            break;
                        }
                        // case 72
                        case 82: {
                            java.lang.String s = input.readStringRequireUtf8();
                            ensureOutputFieldsIsMutable();
                            outputFields_.add(s);
                            break;
                        }
                        // case 82
                        case 88: {
                            consistencyLevel_ = input.readEnum();
                            bitField0_ |= 0x00000400;
                            break;
                        }
                        // case 88
                        case 96: {
                            useDefaultConsistency_ = input.readBool();
                            bitField0_ |= 0x00000800;
                            break;
                        }
                        // case 96
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                // was an endgroup tag
                                done = true;
                            }
                            break;
                        }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private io.milvus.grpc.MsgBase base_;

        private com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.MsgBase, io.milvus.grpc.MsgBase.Builder, io.milvus.grpc.MsgBaseOrBuilder> baseBuilder_;

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>.milvus.proto.common.MsgBase base = 1;</code>
         *
         * @return Whether the base field is set.
         */
        public boolean hasBase() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>.milvus.proto.common.MsgBase base = 1;</code>
         *
         * @return The base.
         */
        public io.milvus.grpc.MsgBase getBase() {
            if (baseBuilder_ == null) {
                return base_ == null ? io.milvus.grpc.MsgBase.getDefaultInstance() : base_;
            } else {
                return baseBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>.milvus.proto.common.MsgBase base = 1;</code>
         */
        public Builder setBase(io.milvus.grpc.MsgBase value) {
            if (baseBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                base_ = value;
            } else {
                baseBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>.milvus.proto.common.MsgBase base = 1;</code>
         */
        public Builder setBase(io.milvus.grpc.MsgBase.Builder builderForValue) {
            if (baseBuilder_ == null) {
                base_ = builderForValue.build();
            } else {
                baseBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>.milvus.proto.common.MsgBase base = 1;</code>
         */
        public Builder mergeBase(io.milvus.grpc.MsgBase value) {
            if (baseBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) && base_ != null && base_ != io.milvus.grpc.MsgBase.getDefaultInstance()) {
                    getBaseBuilder().mergeFrom(value);
                } else {
                    base_ = value;
                }
            } else {
                baseBuilder_.mergeFrom(value);
            }
            if (base_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>.milvus.proto.common.MsgBase base = 1;</code>
         */
        public Builder clearBase() {
            bitField0_ = (bitField0_ & ~0x00000001);
            base_ = null;
            if (baseBuilder_ != null) {
                baseBuilder_.dispose();
                baseBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>.milvus.proto.common.MsgBase base = 1;</code>
         */
        public io.milvus.grpc.MsgBase.Builder getBaseBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return getBaseFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>.milvus.proto.common.MsgBase base = 1;</code>
         */
        public io.milvus.grpc.MsgBaseOrBuilder getBaseOrBuilder() {
            if (baseBuilder_ != null) {
                return baseBuilder_.getMessageOrBuilder();
            } else {
                return base_ == null ? io.milvus.grpc.MsgBase.getDefaultInstance() : base_;
            }
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>.milvus.proto.common.MsgBase base = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.MsgBase, io.milvus.grpc.MsgBase.Builder, io.milvus.grpc.MsgBaseOrBuilder> getBaseFieldBuilder() {
            if (baseBuilder_ == null) {
                baseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<io.milvus.grpc.MsgBase, io.milvus.grpc.MsgBase.Builder, io.milvus.grpc.MsgBaseOrBuilder>(
                        getBase(), getParentForChildren(), isClean());
                base_ = null;
            }
            return baseBuilder_;
        }

        private java.lang.Object dbName_ = "";

        /**
         * <code>string db_name = 2;</code>
         *
         * @return The dbName.
         */
        public java.lang.String getDbName() {
            java.lang.Object ref = dbName_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                dbName_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string db_name = 2;</code>
         *
         * @return The bytes for dbName.
         */
        public com.google.protobuf.ByteString getDbNameBytes() {
            java.lang.Object ref = dbName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                dbName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string db_name = 2;</code>
         *
         * @param value The dbName to set.
         * @return This builder for chaining.
         */
        public Builder setDbName(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            dbName_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>string db_name = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDbName() {
            dbName_ = getDefaultInstance().getDbName();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        /**
         * <code>string db_name = 2;</code>
         *
         * @param value The bytes for dbName to set.
         * @return This builder for chaining.
         */
        public Builder setDbNameBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            dbName_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        private java.lang.Object collectionName_ = "";

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>string collection_name = 3;</code>
         *
         * @return The collectionName.
         */
        public java.lang.String getCollectionName() {
            java.lang.Object ref = collectionName_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                collectionName_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>string collection_name = 3;</code>
         *
         * @return The bytes for collectionName.
         */
        public com.google.protobuf.ByteString getCollectionNameBytes() {
            java.lang.Object ref = collectionName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                collectionName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>string collection_name = 3;</code>
         *
         * @param value The collectionName to set.
         * @return This builder for chaining.
         */
        public Builder setCollectionName(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            collectionName_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>string collection_name = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCollectionName() {
            collectionName_ = getDefaultInstance().getCollectionName();
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>string collection_name = 3;</code>
         *
         * @param value The bytes for collectionName to set.
         * @return This builder for chaining.
         */
        public Builder setCollectionNameBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            collectionName_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        private com.google.protobuf.LazyStringArrayList partitionNames_ = com.google.protobuf.LazyStringArrayList.emptyList();

        private void ensurePartitionNamesIsMutable() {
            if (!partitionNames_.isModifiable()) {
                partitionNames_ = new com.google.protobuf.LazyStringArrayList(partitionNames_);
            }
            bitField0_ |= 0x00000008;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated string partition_names = 4;</code>
         *
         * @return A list containing the partitionNames.
         */
        public com.google.protobuf.ProtocolStringList getPartitionNamesList() {
            partitionNames_.makeImmutable();
            return partitionNames_;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated string partition_names = 4;</code>
         *
         * @return The count of partitionNames.
         */
        public int getPartitionNamesCount() {
            return partitionNames_.size();
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated string partition_names = 4;</code>
         *
         * @param index The index of the element to return.
         * @return The partitionNames at the given index.
         */
        public java.lang.String getPartitionNames(int index) {
            return partitionNames_.get(index);
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated string partition_names = 4;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the partitionNames at the given index.
         */
        public com.google.protobuf.ByteString getPartitionNamesBytes(int index) {
            return partitionNames_.getByteString(index);
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated string partition_names = 4;</code>
         *
         * @param index The index to set the value at.
         * @param value The partitionNames to set.
         * @return This builder for chaining.
         */
        public Builder setPartitionNames(int index, java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensurePartitionNamesIsMutable();
            partitionNames_.set(index, value);
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated string partition_names = 4;</code>
         *
         * @param value The partitionNames to add.
         * @return This builder for chaining.
         */
        public Builder addPartitionNames(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensurePartitionNamesIsMutable();
            partitionNames_.add(value);
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated string partition_names = 4;</code>
         *
         * @param values The partitionNames to add.
         * @return This builder for chaining.
         */
        public Builder addAllPartitionNames(java.lang.Iterable<java.lang.String> values) {
            ensurePartitionNamesIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(values, partitionNames_);
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated string partition_names = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPartitionNames() {
            partitionNames_ = com.google.protobuf.LazyStringArrayList.emptyList();
            bitField0_ = (bitField0_ & ~0x00000008);
            ;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated string partition_names = 4;</code>
         *
         * @param value The bytes of the partitionNames to add.
         * @return This builder for chaining.
         */
        public Builder addPartitionNamesBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensurePartitionNamesIsMutable();
            partitionNames_.add(value);
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        private java.util.List<io.milvus.grpc.SearchRequest> requests_ = java.util.Collections.emptyList();

        private void ensureRequestsIsMutable() {
            if (!((bitField0_ & 0x00000010) != 0)) {
                requests_ = new java.util.ArrayList<io.milvus.grpc.SearchRequest>(requests_);
                bitField0_ |= 0x00000010;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<io.milvus.grpc.SearchRequest, io.milvus.grpc.SearchRequest.Builder, io.milvus.grpc.SearchRequestOrBuilder> requestsBuilder_;

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public java.util.List<io.milvus.grpc.SearchRequest> getRequestsList() {
            if (requestsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(requests_);
            } else {
                return requestsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public int getRequestsCount() {
            if (requestsBuilder_ == null) {
                return requests_.size();
            } else {
                return requestsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public io.milvus.grpc.SearchRequest getRequests(int index) {
            if (requestsBuilder_ == null) {
                return requests_.get(index);
            } else {
                return requestsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public Builder setRequests(int index, io.milvus.grpc.SearchRequest value) {
            if (requestsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureRequestsIsMutable();
                requests_.set(index, value);
                onChanged();
            } else {
                requestsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public Builder setRequests(int index, io.milvus.grpc.SearchRequest.Builder builderForValue) {
            if (requestsBuilder_ == null) {
                ensureRequestsIsMutable();
                requests_.set(index, builderForValue.build());
                onChanged();
            } else {
                requestsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public Builder addRequests(io.milvus.grpc.SearchRequest value) {
            if (requestsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureRequestsIsMutable();
                requests_.add(value);
                onChanged();
            } else {
                requestsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public Builder addRequests(int index, io.milvus.grpc.SearchRequest value) {
            if (requestsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureRequestsIsMutable();
                requests_.add(index, value);
                onChanged();
            } else {
                requestsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public Builder addRequests(io.milvus.grpc.SearchRequest.Builder builderForValue) {
            if (requestsBuilder_ == null) {
                ensureRequestsIsMutable();
                requests_.add(builderForValue.build());
                onChanged();
            } else {
                requestsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public Builder addRequests(int index, io.milvus.grpc.SearchRequest.Builder builderForValue) {
            if (requestsBuilder_ == null) {
                ensureRequestsIsMutable();
                requests_.add(index, builderForValue.build());
                onChanged();
            } else {
                requestsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public Builder addAllRequests(java.lang.Iterable<? extends io.milvus.grpc.SearchRequest> values) {
            if (requestsBuilder_ == null) {
                ensureRequestsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, requests_);
                onChanged();
            } else {
                requestsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public Builder clearRequests() {
            if (requestsBuilder_ == null) {
                requests_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
            } else {
                requestsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public Builder removeRequests(int index) {
            if (requestsBuilder_ == null) {
                ensureRequestsIsMutable();
                requests_.remove(index);
                onChanged();
            } else {
                requestsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public io.milvus.grpc.SearchRequest.Builder getRequestsBuilder(int index) {
            return getRequestsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public io.milvus.grpc.SearchRequestOrBuilder getRequestsOrBuilder(int index) {
            if (requestsBuilder_ == null) {
                return requests_.get(index);
            } else {
                return requestsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public java.util.List<? extends io.milvus.grpc.SearchRequestOrBuilder> getRequestsOrBuilderList() {
            if (requestsBuilder_ != null) {
                return requestsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(requests_);
            }
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public io.milvus.grpc.SearchRequest.Builder addRequestsBuilder() {
            return getRequestsFieldBuilder().addBuilder(io.milvus.grpc.SearchRequest.getDefaultInstance());
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public io.milvus.grpc.SearchRequest.Builder addRequestsBuilder(int index) {
            return getRequestsFieldBuilder().addBuilder(index, io.milvus.grpc.SearchRequest.getDefaultInstance());
        }

        /**
         * <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
         */
        public java.util.List<io.milvus.grpc.SearchRequest.Builder> getRequestsBuilderList() {
            return getRequestsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<io.milvus.grpc.SearchRequest, io.milvus.grpc.SearchRequest.Builder, io.milvus.grpc.SearchRequestOrBuilder> getRequestsFieldBuilder() {
            if (requestsBuilder_ == null) {
                requestsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<io.milvus.grpc.SearchRequest, io.milvus.grpc.SearchRequest.Builder, io.milvus.grpc.SearchRequestOrBuilder>(
                        requests_, ((bitField0_ & 0x00000010) != 0), getParentForChildren(), isClean());
                requests_ = null;
            }
            return requestsBuilder_;
        }

        private java.util.List<io.milvus.grpc.KeyValuePair> rankParams_ = java.util.Collections.emptyList();

        private void ensureRankParamsIsMutable() {
            if (!((bitField0_ & 0x00000020) != 0)) {
                rankParams_ = new java.util.ArrayList<io.milvus.grpc.KeyValuePair>(rankParams_);
                bitField0_ |= 0x00000020;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<io.milvus.grpc.KeyValuePair, io.milvus.grpc.KeyValuePair.Builder, io.milvus.grpc.KeyValuePairOrBuilder> rankParamsBuilder_;

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public java.util.List<io.milvus.grpc.KeyValuePair> getRankParamsList() {
            if (rankParamsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(rankParams_);
            } else {
                return rankParamsBuilder_.getMessageList();
            }
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public int getRankParamsCount() {
            if (rankParamsBuilder_ == null) {
                return rankParams_.size();
            } else {
                return rankParamsBuilder_.getCount();
            }
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public io.milvus.grpc.KeyValuePair getRankParams(int index) {
            if (rankParamsBuilder_ == null) {
                return rankParams_.get(index);
            } else {
                return rankParamsBuilder_.getMessage(index);
            }
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public Builder setRankParams(int index, io.milvus.grpc.KeyValuePair value) {
            if (rankParamsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureRankParamsIsMutable();
                rankParams_.set(index, value);
                onChanged();
            } else {
                rankParamsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public Builder setRankParams(int index, io.milvus.grpc.KeyValuePair.Builder builderForValue) {
            if (rankParamsBuilder_ == null) {
                ensureRankParamsIsMutable();
                rankParams_.set(index, builderForValue.build());
                onChanged();
            } else {
                rankParamsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public Builder addRankParams(io.milvus.grpc.KeyValuePair value) {
            if (rankParamsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureRankParamsIsMutable();
                rankParams_.add(value);
                onChanged();
            } else {
                rankParamsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public Builder addRankParams(int index, io.milvus.grpc.KeyValuePair value) {
            if (rankParamsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureRankParamsIsMutable();
                rankParams_.add(index, value);
                onChanged();
            } else {
                rankParamsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public Builder addRankParams(io.milvus.grpc.KeyValuePair.Builder builderForValue) {
            if (rankParamsBuilder_ == null) {
                ensureRankParamsIsMutable();
                rankParams_.add(builderForValue.build());
                onChanged();
            } else {
                rankParamsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public Builder addRankParams(int index, io.milvus.grpc.KeyValuePair.Builder builderForValue) {
            if (rankParamsBuilder_ == null) {
                ensureRankParamsIsMutable();
                rankParams_.add(index, builderForValue.build());
                onChanged();
            } else {
                rankParamsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public Builder addAllRankParams(java.lang.Iterable<? extends io.milvus.grpc.KeyValuePair> values) {
            if (rankParamsBuilder_ == null) {
                ensureRankParamsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, rankParams_);
                onChanged();
            } else {
                rankParamsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public Builder clearRankParams() {
            if (rankParamsBuilder_ == null) {
                rankParams_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000020);
                onChanged();
            } else {
                rankParamsBuilder_.clear();
            }
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public Builder removeRankParams(int index) {
            if (rankParamsBuilder_ == null) {
                ensureRankParamsIsMutable();
                rankParams_.remove(index);
                onChanged();
            } else {
                rankParamsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public io.milvus.grpc.KeyValuePair.Builder getRankParamsBuilder(int index) {
            return getRankParamsFieldBuilder().getBuilder(index);
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public io.milvus.grpc.KeyValuePairOrBuilder getRankParamsOrBuilder(int index) {
            if (rankParamsBuilder_ == null) {
                return rankParams_.get(index);
            } else {
                return rankParamsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public java.util.List<? extends io.milvus.grpc.KeyValuePairOrBuilder> getRankParamsOrBuilderList() {
            if (rankParamsBuilder_ != null) {
                return rankParamsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(rankParams_);
            }
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public io.milvus.grpc.KeyValuePair.Builder addRankParamsBuilder() {
            return getRankParamsFieldBuilder().addBuilder(io.milvus.grpc.KeyValuePair.getDefaultInstance());
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public io.milvus.grpc.KeyValuePair.Builder addRankParamsBuilder(int index) {
            return getRankParamsFieldBuilder().addBuilder(index, io.milvus.grpc.KeyValuePair.getDefaultInstance());
        }

        /**
         * <pre>
         * must
         * </pre>
         *
         * <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
         */
        public java.util.List<io.milvus.grpc.KeyValuePair.Builder> getRankParamsBuilderList() {
            return getRankParamsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<io.milvus.grpc.KeyValuePair, io.milvus.grpc.KeyValuePair.Builder, io.milvus.grpc.KeyValuePairOrBuilder> getRankParamsFieldBuilder() {
            if (rankParamsBuilder_ == null) {
                rankParamsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<io.milvus.grpc.KeyValuePair, io.milvus.grpc.KeyValuePair.Builder, io.milvus.grpc.KeyValuePairOrBuilder>(
                        rankParams_, ((bitField0_ & 0x00000020) != 0), getParentForChildren(), isClean());
                rankParams_ = null;
            }
            return rankParamsBuilder_;
        }

        private long travelTimestamp_;

        /**
         * <code>uint64 travel_timestamp = 7;</code>
         *
         * @return The travelTimestamp.
         */
        @java.lang.Override
        public long getTravelTimestamp() {
            return travelTimestamp_;
        }

        /**
         * <code>uint64 travel_timestamp = 7;</code>
         *
         * @param value The travelTimestamp to set.
         * @return This builder for chaining.
         */
        public Builder setTravelTimestamp(long value) {
            travelTimestamp_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        /**
         * <code>uint64 travel_timestamp = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearTravelTimestamp() {
            bitField0_ = (bitField0_ & ~0x00000040);
            travelTimestamp_ = 0L;
            onChanged();
            return this;
        }

        private long guaranteeTimestamp_;

        /**
         * <pre>
         * guarantee_timestamp
         * </pre>
         *
         * <code>uint64 guarantee_timestamp = 8;</code>
         *
         * @return The guaranteeTimestamp.
         */
        @java.lang.Override
        public long getGuaranteeTimestamp() {
            return guaranteeTimestamp_;
        }

        /**
         * <pre>
         * guarantee_timestamp
         * </pre>
         *
         * <code>uint64 guarantee_timestamp = 8;</code>
         *
         * @param value The guaranteeTimestamp to set.
         * @return This builder for chaining.
         */
        public Builder setGuaranteeTimestamp(long value) {
            guaranteeTimestamp_ = value;
            bitField0_ |= 0x00000080;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * guarantee_timestamp
         * </pre>
         *
         * <code>uint64 guarantee_timestamp = 8;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearGuaranteeTimestamp() {
            bitField0_ = (bitField0_ & ~0x00000080);
            guaranteeTimestamp_ = 0L;
            onChanged();
            return this;
        }

        private boolean notReturnAllMeta_;

        /**
         * <code>bool not_return_all_meta = 9;</code>
         *
         * @return The notReturnAllMeta.
         */
        @java.lang.Override
        public boolean getNotReturnAllMeta() {
            return notReturnAllMeta_;
        }

        /**
         * <code>bool not_return_all_meta = 9;</code>
         *
         * @param value The notReturnAllMeta to set.
         * @return This builder for chaining.
         */
        public Builder setNotReturnAllMeta(boolean value) {
            notReturnAllMeta_ = value;
            bitField0_ |= 0x00000100;
            onChanged();
            return this;
        }

        /**
         * <code>bool not_return_all_meta = 9;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearNotReturnAllMeta() {
            bitField0_ = (bitField0_ & ~0x00000100);
            notReturnAllMeta_ = false;
            onChanged();
            return this;
        }

        private com.google.protobuf.LazyStringArrayList outputFields_ = com.google.protobuf.LazyStringArrayList.emptyList();

        private void ensureOutputFieldsIsMutable() {
            if (!outputFields_.isModifiable()) {
                outputFields_ = new com.google.protobuf.LazyStringArrayList(outputFields_);
            }
            bitField0_ |= 0x00000200;
        }

        /**
         * <code>repeated string output_fields = 10;</code>
         *
         * @return A list containing the outputFields.
         */
        public com.google.protobuf.ProtocolStringList getOutputFieldsList() {
            outputFields_.makeImmutable();
            return outputFields_;
        }

        /**
         * <code>repeated string output_fields = 10;</code>
         *
         * @return The count of outputFields.
         */
        public int getOutputFieldsCount() {
            return outputFields_.size();
        }

        /**
         * <code>repeated string output_fields = 10;</code>
         *
         * @param index The index of the element to return.
         * @return The outputFields at the given index.
         */
        public java.lang.String getOutputFields(int index) {
            return outputFields_.get(index);
        }

        /**
         * <code>repeated string output_fields = 10;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the outputFields at the given index.
         */
        public com.google.protobuf.ByteString getOutputFieldsBytes(int index) {
            return outputFields_.getByteString(index);
        }

        /**
         * <code>repeated string output_fields = 10;</code>
         *
         * @param index The index to set the value at.
         * @param value The outputFields to set.
         * @return This builder for chaining.
         */
        public Builder setOutputFields(int index, java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureOutputFieldsIsMutable();
            outputFields_.set(index, value);
            bitField0_ |= 0x00000200;
            onChanged();
            return this;
        }

        /**
         * <code>repeated string output_fields = 10;</code>
         *
         * @param value The outputFields to add.
         * @return This builder for chaining.
         */
        public Builder addOutputFields(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureOutputFieldsIsMutable();
            outputFields_.add(value);
            bitField0_ |= 0x00000200;
            onChanged();
            return this;
        }

        /**
         * <code>repeated string output_fields = 10;</code>
         *
         * @param values The outputFields to add.
         * @return This builder for chaining.
         */
        public Builder addAllOutputFields(java.lang.Iterable<java.lang.String> values) {
            ensureOutputFieldsIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(values, outputFields_);
            bitField0_ |= 0x00000200;
            onChanged();
            return this;
        }

        /**
         * <code>repeated string output_fields = 10;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearOutputFields() {
            outputFields_ = com.google.protobuf.LazyStringArrayList.emptyList();
            bitField0_ = (bitField0_ & ~0x00000200);
            ;
            onChanged();
            return this;
        }

        /**
         * <code>repeated string output_fields = 10;</code>
         *
         * @param value The bytes of the outputFields to add.
         * @return This builder for chaining.
         */
        public Builder addOutputFieldsBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureOutputFieldsIsMutable();
            outputFields_.add(value);
            bitField0_ |= 0x00000200;
            onChanged();
            return this;
        }

        private int consistencyLevel_ = 0;

        /**
         * <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
         *
         * @return The enum numeric value on the wire for consistencyLevel.
         */
        @java.lang.Override
        public int getConsistencyLevelValue() {
            return consistencyLevel_;
        }

        /**
         * <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
         *
         * @param value The enum numeric value on the wire for consistencyLevel to set.
         * @return This builder for chaining.
         */
        public Builder setConsistencyLevelValue(int value) {
            consistencyLevel_ = value;
            bitField0_ |= 0x00000400;
            onChanged();
            return this;
        }

        /**
         * <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
         *
         * @return The consistencyLevel.
         */
        @java.lang.Override
        public io.milvus.grpc.ConsistencyLevel getConsistencyLevel() {
            io.milvus.grpc.ConsistencyLevel result = io.milvus.grpc.ConsistencyLevel.forNumber(consistencyLevel_);
            return result == null ? io.milvus.grpc.ConsistencyLevel.UNRECOGNIZED : result;
        }

        /**
         * <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
         *
         * @param value The consistencyLevel to set.
         * @return This builder for chaining.
         */
        public Builder setConsistencyLevel(io.milvus.grpc.ConsistencyLevel value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000400;
            consistencyLevel_ = value.getNumber();
            onChanged();
            return this;
        }

        /**
         * <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearConsistencyLevel() {
            bitField0_ = (bitField0_ & ~0x00000400);
            consistencyLevel_ = 0;
            onChanged();
            return this;
        }

        private boolean useDefaultConsistency_;

        /**
         * <code>bool use_default_consistency = 12;</code>
         *
         * @return The useDefaultConsistency.
         */
        @java.lang.Override
        public boolean getUseDefaultConsistency() {
            return useDefaultConsistency_;
        }

        /**
         * <code>bool use_default_consistency = 12;</code>
         *
         * @param value The useDefaultConsistency to set.
         * @return This builder for chaining.
         */
        public Builder setUseDefaultConsistency(boolean value) {
            useDefaultConsistency_ = value;
            bitField0_ |= 0x00000800;
            onChanged();
            return this;
        }

        /**
         * <code>bool use_default_consistency = 12;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearUseDefaultConsistency() {
            bitField0_ = (bitField0_ & ~0x00000800);
            useDefaultConsistency_ = false;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        // @@protoc_insertion_point(builder_scope:milvus.proto.milvus.SearchRequestV2)
    }

    // @@protoc_insertion_point(class_scope:milvus.proto.milvus.SearchRequestV2)
    private static final io.milvus.grpc.SearchRequestV2 DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new io.milvus.grpc.SearchRequestV2();
    }

    public static io.milvus.grpc.SearchRequestV2 getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchRequestV2> PARSER = new com.google.protobuf.AbstractParser<SearchRequestV2>() {

        @java.lang.Override
        public SearchRequestV2 parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<SearchRequestV2> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequestV2> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public io.milvus.grpc.SearchRequestV2 getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
