// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto
package io.milvus.grpc;

public interface VectorFieldOrBuilder extends // @@protoc_insertion_point(interface_extends:milvus.proto.schema.VectorField)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 dim = 1;</code>
     *
     * @return The dim.
     */
    long getDim();

    /**
     * <code>.milvus.proto.schema.FloatArray float_vector = 2;</code>
     *
     * @return Whether the floatVector field is set.
     */
    boolean hasFloatVector();

    /**
     * <code>.milvus.proto.schema.FloatArray float_vector = 2;</code>
     *
     * @return The floatVector.
     */
    io.milvus.grpc.FloatArray getFloatVector();

    /**
     * <code>.milvus.proto.schema.FloatArray float_vector = 2;</code>
     */
    io.milvus.grpc.FloatArrayOrBuilder getFloatVectorOrBuilder();

    /**
     * <code>bytes binary_vector = 3;</code>
     *
     * @return Whether the binaryVector field is set.
     */
    boolean hasBinaryVector();

    /**
     * <code>bytes binary_vector = 3;</code>
     *
     * @return The binaryVector.
     */
    com.google.protobuf.ByteString getBinaryVector();

    /**
     * <code>bytes float16_vector = 4;</code>
     *
     * @return Whether the float16Vector field is set.
     */
    boolean hasFloat16Vector();

    /**
     * <code>bytes float16_vector = 4;</code>
     *
     * @return The float16Vector.
     */
    com.google.protobuf.ByteString getFloat16Vector();

    /**
     * <code>bytes bfloat16_vector = 5;</code>
     *
     * @return Whether the bfloat16Vector field is set.
     */
    boolean hasBfloat16Vector();

    /**
     * <code>bytes bfloat16_vector = 5;</code>
     *
     * @return The bfloat16Vector.
     */
    com.google.protobuf.ByteString getBfloat16Vector();

    io.milvus.grpc.VectorField.DataCase getDataCase();
}
