name: Build (on push)

on:
  push:
    branches:
      - "main"
      - "documentation-test"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  documentation-check:
    name: Documentation check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build with Maven
        run: ./mvnw -B clean install -DskipTests -Dno-format -ntp

      - name: Validate documentation
        run: |
          STATUS=$(git status --porcelain docs/modules/ROOT/pages/includes/)
          if [ -n "$STATUS" ]; then
            echo "Generated documentation is not up to date."
            echo "'git status' output after rebuilding the docs:"
            git status
            echo "To fix this (make sure you use JDK 22+ so that all modules are activated):"
            echo "  1. Run: mvn clean install"
            echo "  2. Commit the generated documentation files"
            exit 1
          else
            echo "Generated documentation is up to date."
          fi

